#!/bin/sh
#
# 2012 SwellPath, Inc.
# Christian G. Warden <cwarden@xerus.org>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage LuaRocks packages
#


if [ -f "$__object/parameter/name" ]; then
   name="$(cat "$__object/parameter/name")"
else
   name="$__object_id"
fi

if [ -f "$__object/parameter/state" ]; then
   state="$(cat "$__object/parameter/state")"
else
   state="installed"
fi
is_installed="$(grep "(installed)" "$__object/explorer/pkg_status" || true)"

case "$state" in
   installed)
      # Install only if non-existent
      if [ -z "$is_installed" ]; then
         echo luarocks install \"$name\"
      fi
   ;;
   removed)
      # Remove only if existent
      if [ -n "$is_installed" ]; then
         echo luarocks remove \"$name\"
      fi
   ;;
   *)
      echo "Unknown state: $state" >&2
      exit 1
   ;;
esac
