#!/bin/sh
#
# 2013 Chase Allen James (nx-cdist at nu-ex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Prefixes all remote commands with sudo.
#
# This command assumes your ssh configuration is already set up
# in ~/.ssh/config.
#
# Usage:
#  cdist config --remote-exec "/path/to/this/script" target_host
#

host="$1"; shift
ssh -q "$host" sudo sh -c \""$@"\"
