#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

value_is="$(cat "$__object/explorer/value")"
value_should="$(cat "$__object/parameter/value")"

key="$(cat "$__object/parameter/key")"
file="$(cat "$__object/parameter/file")"
delimiter="$(cat "$__object/parameter/delimiter")"

if [ "$value_is" != "$value_should" ]; then
   case "$value_is" in
      __NOTSET__)
         # add key and value
         echo "echo \"${key}${delimiter}${value_should}\" >> \"$file\""
      ;;
      *)
         if [ "$value_should" = '__NOTSET__' ]; then
            # remove key and value
            cat << DONE
sed -i '/^${key}/d' "$file"
DONE
         else
            # change value
            cat << DONE
awk -F "$delimiter" '
/${key}${delimiter}*/{gsub(/$value_is/, "$value_should")};{print}' "$file" > "${file}+" \
&& mv "${file}+" "$file"

DONE
         fi
      ;;
   esac
fi

