#!/bin/sh
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

state_is="$(cat "$__object/explorer/state")"
state_should=present
[ -f "$__object/parameter/state" ] && state_should="$(cat "$__object/parameter/state")"

branch=master
[ -f "$__object/parameter/branch" ] && branch="$(cat "$__object/parameter/branch")"

source="$(cat "$__object/parameter/source")"

destination="/$__object_id"

[ "$state_should" = "$state_is" ] && exit 0

case $state_should in
    present)
        echo git clone --quiet --branch "$branch" "$source" "$destination"
    ;;
    # Handled in manifest
    absent)
    ;;

    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
