#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

#
# Ensure hostname is setup
#
__file /etc/hostname --source "$__object/parameter/hostname"

# All Linux distros have those
for pkg in dvdbackup mplayer x11vnc xfmpc; do
   __package $pkg --state installed
done

case "$(cat "$__global/explorer/os")" in
   debian|ubuntu)
      require="__package/zsh" __user lyni --uid 1000 --shell /bin/zsh

      for pkg in chromium-browser xfce4 xtightvncviewer; do
         __package $pkg --state installed
      done

      # Make slim default desktop on Debian/Ubuntu
      __debconf_set_selections slim --file "$__type/files/slim-preseed"
      require="__debconf_set_selections/slim" __package_apt slim --state installed
   ;;
esac

# Including gaming fun - not within examples, too big for core inclusion :-p
# __nico_dosbox
