#!/bin/sh
#
# 2011-2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

destination="/$__object_id"
state_should="$(cat "$__object/parameter/state")"
type="$(cat "$__object/explorer/type")"

[ "$state_should" = "exists" -a "$type" = "file" ] && exit 0 # nothing to do

upload_file=
create_file=
if [ "$state_should" = "present" -o "$state_should" = "exists" ]; then
   if [ ! -f "$__object/parameter/source" ]; then
      create_file=1
      echo create >> "$__messages_out"
   else
      source="$(cat "$__object/parameter/source")"
      if [ "$source" = "-" ]; then
         source="$__object/stdin"
      fi
      if [ ! -f "$source" ]; then
         echo "Source \"$source\" does not exist." >&2
         exit 1
      else
         if [ "$type" != "file" ]; then
            # destination is not a regular file, upload source to replace it
            upload_file=1
         else
            local_cksum="$(cksum < "$source")"
            remote_cksum="$(cat "$__object/explorer/cksum")"
            if [ "$local_cksum" != "$remote_cksum" ]; then
               # destination is a regular file, but not the right one
               upload_file=1
            fi
         fi
      fi
   fi
   if [ "$create_file" -o "$upload_file" ]; then
      # tell gencode-remote that we created or uploaded a file and that it must
      # set all attributes no matter what the explorer retreived
      mkdir "$__object/files"
      touch "$__object/files/set-attributes"

      # upload file to temp location
      tempfile_template="${destination}.cdist.XXXXXXXXXX"
      cat << DONE
destination_upload="\$($__remote_exec $__target_host "mktemp $tempfile_template")"
DONE
      if [ "$upload_file" ]; then
         echo upload >> "$__messages_out"
         cat << DONE
$__remote_copy "$source" "${__target_host}:\$destination_upload"
DONE
      fi
# move uploaded file into place
cat << DONE
$__remote_exec $__target_host "rm -rf \"$destination\"; mv \"\$destination_upload\" \"$destination\""
DONE
   fi
fi
