#!/bin/sh
#
# 2011-2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

destination="/$__object_id"
state_should="$(cat "$__object/parameter/state")"
type="$(cat "$__object/explorer/type")"
stat_file="$__object/explorer/stat"


get_current_value() {
   if [ -s "$stat_file" ]; then
      _name="$1"
      _value="$2"
      case "$_value" in
         [0-9]*)
            _index=2
         ;;
         *)
            _index=3
         ;;
      esac
      awk '/'"$_name"':/ { print $'$_index' }' "$stat_file"
      unset _name _value _index
   fi
}

set_group() {
   echo chgrp \"$1\" \"$destination\"
}

set_owner() {
   echo chown \"$1\" \"$destination\"
}

set_mode() {
   echo chmod \"$1\" \"$destination\"
}

set_attributes=
case "$state_should" in
   present|exists)
      if [ -f "$__object/files/destination_upload" ]; then
         # we uploaded a file, move it into place and set all attributes
         destination_upload="$(cat "$__object/files/destination_upload")"
         set_attributes=1
         if [ "$type" = "directory" ]; then
            # our destination is currently a directory, move it out of the way,
            cat << DONE
destination_old="\$(mktemp "${destination}.cdist.XXXXXXXXXX")"
mv "$destination" "\$destination_old"
DONE
         fi

         # move our upload into place
         cat << DONE
mv "$destination_upload" "$destination"
DONE

         if [ "$type" = "directory" ]; then
            # delete the legacy directory
            cat << DONE
rm -rf "\$destination_old"
DONE
         fi
      fi

      # Note: Mode - needs to happen last as a chown/chgrp can alter mode by
      #  clearing S_ISUID and S_ISGID bits (see chown(2))
      for attribute in group owner mode; do
         if [ -f "$__object/parameter/$attribute" ]; then
            value_should="$(cat "$__object/parameter/$attribute")"
            value_is="$(get_current_value "$attribute" "$value_should")"
            if [ "$set_attributes" -o "$value_should" != "$value_is" ]; then
               "set_$attribute" "$value_should"
            fi
         fi
      done
   ;;

   absent)
      # FIXME: only delete if it's a file? or no matter what?
      if [ "$type" = "file" ]; then
         echo rm -f \"$destination\"
      fi
   ;;

   *)
      echo "Unknown state: $state_should" >&2
      exit 1
   ;;
esac
