#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

name="$__object_id"
target_uri="schroot://$__target_host/$name"
remote="$__type/files/remote-schroot-uri"

cdist_args="-v"
[ "$__debug" = "yes" ] && cdist_args="$cdist_args -d"

cat << DONE
export __remote_exec="$remote exec"
export __remote_copy="$remote copy"
cdist $cdist_args config $target_uri
DONE
