#!/bin/sh
#
# 2012 Chase Allen James <nx-cdist@nu-ex.com>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
state_is="$(cat "$__object/explorer/state")"
state_should="$(cat "$__object/parameter/state")"
if [ "$state_is" != "$state_should" ]; then
  case "$state_should" in
    present)
      # echo install commands to target
      cat "$__type/files/install.sh"
    ;;
    absent)
      echo "rm /etc/profile.d/rbenv.sh"
      echo "rm -rf /usr/local/rbenv"
      echo "rm -rf /usr/local/share/ruby-build"
      echo "rm /usr/local/bin/rbenv-install"
      echo "rm /usr/local/bin/ruby-build"
    ;;
  esac
fi
