#!/bin/sh
# Try to detect lib directory with the XS files
# since we build with thread support, this should be, err
# hum, well "safe".
MYPWD=`dirname $0`

# Get an absolute path if needed
[ "$MYPWD" = "." ] && MYPWD=`pwd`

if [ ! -f "$MYPWD/perl/lib/site_perl/5.12.1/FusionInventory/Agent/Task/NetDiscovery/Manufacturer/HewlettPackard.pm" ]; then
  echo "Your installation is not complete. It's very likely you used a non GNU tar to"
  echo "extract the agent distribution."
  echo "POSIX tar are not able to extract tarball with path length > 100 characters."
  echo ""
  echo " -- PLEASE use GNU tar! --"
  exit 1
fi



XSDIR=`ls -d $MYPWD/perl/lib/5.12.1/*-thread-*`
XSDIR=$XSDIR:`ls -d $MYPWD/perl/lib/site_perl/5.12.1/*-thread-*`

# For memconf
PATH=$MYPWD/perl/bin:$PATH
REALLIB="$MYPWD/perl/lib/5.12.1:$MYPWD/perl/lib/site_perl/5.12.1:$XSDIR"

export PATH
export REALLIB

echo $MYPWD
cd $MYPWD
exec $MYPWD/perl/bin/perl $MYPWD/perl/bin/fusioninventory-agent --conf-file=./agent.cfg $*
