#!/bin/bash
# bootstrap a new client

if [ -z "$1" ]; then
  echo "Usage: $0 <client>"
  exit 2
fi

local=/cdist/cdist/local
C=$1
DH=/deploy/scripts/deployHelper.pl

$DH --sysinfo=$C > /dev/null
if [ $? -ne 0 ]; then
  # it's not in any stacks, maybe it's independent and just in groups?
  ${local}/lib/getGroups.pl $C > /dev/null
  if [ $? -ne 0 ]; then
    echo "ERROR: $C is not a recognized system.  I know about these:"
    stacksys=$($DH --allsystems)
    groupsys=$(${local}/lib/getGroups.pl --listall)
    echo $stacksys $groupsys | sed -e 's/ /\n/g' | sort -u
    exit 1
  fi
fi

$local/bootstrap/bootstrap_cdist.sh $C
if [ $? -ne 0 ]; then
  echo "Error bootstrapping... bailing"
  exit 2
fi

$local/cdist_wrapper -v $C

