#!/bin/bash
# bootstrap a new client

if [ -z "$1" ]; then
  echo "Usage: $0 <client>"
  exit 2
fi

local=/cdist/cdist/local
. ${local}/lib/functions

C=$1

$DH --sysinfo=$C > /dev/null
if [ $? -ne 0 ]; then
  # it's not in any stacks, maybe it's independent and just in groups?
  ${local}/lib/getGroups.pl $C > /dev/null
  if [ $? -ne 0 ]; then
    echo "ERROR: $C is not a recognized system.  I know about these:"
    printKnownSystems $s
    exit 1
  fi
fi

$local/bootstrap/bootstrap_cdist.sh $C
if [ $? -ne 0 ]; then
  echo "Error bootstrapping... bailing"
  exit 2
fi

$local/cdist_wrapper -v $C

