#!/bin/sh -e

state_is="$( cat "$__object/explorer/state" )"

state_should="$( cat "$__object/parameter/state" )"

if [ "$state_is" = "$state_should" ]
then
    exit 0
fi

if [ -f "$__object/parameter/name" ]
then
    name="$( cat "$__object/parameter/name" )"
else
    name="$__object_id"
fi

case "$state_should" in
    present)
        echo "mysql -e 'create database \`$name\`'"
        echo "create database $name" >> "$__messages_out"
    ;;
    absent)
        echo "mysql -e 'drop database \`$name\`'"
        echo "drop database $name" >> "$__messages_out"
    ;;
esac
