#!/bin/sh -e
#
# 2020 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/user" ]
then
    user="$( cat "$__object/parameter/user" )"
fi

if [ -f "$__object/parameter/password" ]
then
    password="$( cat "$__object/parameter/password" )"
fi

if [ -n "$user" ] && [ -n "$password" ]
then
    if [ -f "$__object/parameter/name" ]
    then
        database="$( cat "$__object/parameter/name" )"
    else
        database="$__object_id"
    fi

    state_should="$( cat "$__object/parameter/state" )"

    __mysql_user "$user" \
        --password "$password" \
        --state "$state_should"

    # removing user should remove all user's privileges
    require="__mysql_user/$user" \
        __mysql_privileges "$database/$user" \
            --database "$database" \
            --user "$user" \
            --state "$state_should"
fi
