#!/bin/sh -e

privileges="$( cat "$__object/parameter/privileges" )"

database="$( cat "$__object/parameter/database" )"

table="$( cat "$__object/parameter/table" )"

user="$( cat "$__object/parameter/user" )"

host="$( cat "$__object/parameter/host" )"

check_privileges="$( 
    mysql -B -N -e "show grants for '$user'@'$host'" \
        | grep -Ei "^grant $privileges on .$database.\..$table. to " || true )"

if [ -n "$check_privileges" ]
then
    echo 'present'
else
    echo 'absent'
fi
