#!/bin/sh -e
#
# 2020 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

privileges="$( cat "$__object/parameter/privileges" )"

database="$( cat "$__object/parameter/database" )"

table="$( cat "$__object/parameter/table" )"

user="$( cat "$__object/parameter/user" )"

host="$( cat "$__object/parameter/host" )"

check_privileges="$( 
    mysql -B -N -e "show grants for '$user'@'$host'" \
        | grep -Ei "^grant $privileges on .$database.\..$table. to " || true )"

if [ -n "$check_privileges" ]
then
    echo 'present'
else
    echo 'absent'
fi
