#!/bin/sh
#
# 2011 Aurélien Bondis  aurelien.bondis AT gmail DOT com
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# This type allows to send a public ssh key from a user to the
# authorized_keys of another
#
#require="__package openssh-server --state installed"

# If a source user was given, use its public key,
# otherwise default to using root's public key.
if [ -f "$__object/parameter/srcuser" ]; then
  srcuser="$(cat "$__object/parameter/srcuser")"
  pubkey="$(cat "/home/${srcuser}/.ssh/id_rsa.pub")"
else
  pubkey="$(cat /root/.ssh/id_rsa.pub)"
fi

# Set the destination user and remote ssh directory.
# Default to root if no destination user was given.
if [ -f "$__object/parameter/dstuser" ]; then
  dstuser="$(cat "$__object/parameter/dstuser")"
  sshdir="/home/${dstuser}/.ssh"
else
  dstuser="root"
  sshdir="/root/.ssh"
fi

# Set up the remote ssh directory with correct permissions
__directory $sshdir --owner $dstuser --mode 700
require="__directory${sshdir}" __file "${sshdir}/authorized_keys" \
  --owner $dstuser --mode 640
  
# Add the pubkey to the destination user's authorized_keys file
require="__file${sshdir}/authorized_keys" __addifnosuchline sshkey --file \
 "${sshdir}/authorized_keys" --line "${pubkey}"
