#!/bin/sh
#
# 2014 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

state_should="$(cat "$__object/parameter/state")"
num_vdi_lines=$(wc -l < "$__object/explorer/list")
name="$__object_id"


if [ "$num_vdi_lines" = 1 ]; then
    state_is=present
else
    state_is=absent
fi

[ "$state_is" = "$state_should" ] && exit 0

case "$state_should" in
    present)
        size="$(cat "$__object/parameter/size")"
        echo "dog vdi create '$name' '$size'"
    ;;
    absent)
        echo "dog vdi delete '$name'"
    ;;
esac
