#!/bin/sh -e
#
# 2020 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/name" ]
then
    name="$( cat "$__object/parameter/name" )"
else
    name="$__object_id"
fi

if [ -f "$__object/parameter/password" ]
then
    password="$( cat "$__object/parameter/password" )"
else
    password=''
fi

host="$( cat "$__object/parameter/host" )"

check_user="$( mysql -B -N -e "select user from mysql.user where user = '$name' and host = '$host'" )"

if [ -n "$check_user" ]
then
    if [ -n "$password" ]
    then
        check_password="$( mysql -B -N -e "select user from mysql.user where user = '$name' and host = '$host' and password = password( '$password' )" )"
    fi

    if [ -n "$password" ] && [ -z "$check_password" ]
    then
        echo 'change-password'
    else
        echo 'present'
    fi
else
    echo 'absent'
fi
