#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

name="$__object_id"
entryfile="$__object/files/entry"

user="$(cat "$__object/parameter/user")"
state_should="$(cat "$__object/parameter/state" 2>/dev/null || echo present)"
state_is=$(diff -q "$entryfile" "$__object/explorer/entry" \
   && echo present \
   || echo absent
)

# Short circuit - no need to change something
[ "$state_is" = "$state_should" ] && exit 0

case "$state_should" in
    present)
        cat << eof
tmp=\$(mktemp)
crontab -u $user -l > \$tmp 2>/dev/null || true
cat >> \$tmp << EOC
$(cat "$entryfile")"
EOC
crontab -u \"$user\" \$tmp
rm \$tmp
eof
    ;;

    absent)
        # defined in type manifest
        prefix="#cdist:__cron/$name"
        suffix="#/cdist:__cron/$name"
        cat << eof
crontab -u $user -l | awk -v prefix="$prefix" -v suffix="$suffix" '
{
   if (index(\$0,prefix)) {
      triggered=1
   }
   if (triggered) {
      if (index(\$0,suffix)) {
            triggered=0
      }
   } else {
      print
   }
}
' | crontab -u $user -
eof
    ;;
esac
