#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os="$(cat "$__global/explorer/os")"
user="$(cat "$__object/parameter/user")"
state_should="$(cat "$__object/parameter/state")"
state_is=$(diff -q "$__object/parameter/entry" "$__object/explorer/entry" \
   && echo present \
   || echo absent
)

# FreeBSD mktemp doesn't allow execution without at least one param
if [ "$os" = "freebsd" ]; then
   mktemp="mktemp -t tmp"
else
   mktemp="mktemp"
fi

if [ "$state_is" != "$state_should" ]; then
   case "$state_should" in
      present)
         cat << DONE
tmp=\$($mktemp)
crontab -u $user -l > \$tmp
cat >> \$tmp << EOC
$(cat "$__object/parameter/entry")
EOC
crontab -u $user \$tmp
rm \$tmp
DONE
      ;;
      absent)
         # defined in type manifest
         prefix="$(cat "$__object/parameter/prefix")"
         suffix="$(cat "$__object/parameter/suffix")"
         cat << DONE
crontab -u $user -l | awk -v prefix="$prefix" -v suffix="$suffix" '
{
   if (index(\$0,prefix)) {
      triggered=1
   }
   if (triggered) {
      if (index(\$0,suffix)) {
            triggered=0
      }
   } else {
      print
   }
}
' | crontab -u $user -
DONE
      ;;
   esac
fi
