#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __remote_exec script to run cdist against a chroot on the target host over ssh.
#
# Usage:
#  cdist config --remote-exec "/path/to/this/script schroot-chroot-name" target_host
#

log() {
   #echo "$@" | logger -t "cdist-schroot-exec"
   :
}

chroot_name="$1"; shift
target_host="$1"; shift

code="ssh -o User=root -q $target_host schroot -c $chroot_name -- $@"

log "target_host: $target_host"
log "chroot_name: $chroot_name"
log "@: $@"
log "code: $code"

# run in remote chroot
$code

log "-----"
