#!/bin/sh -e
#
# 2018-2019 Thomas Eckert (tom at it-eckert.de)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.

confdir=$(cat "$__object/parameter/confdir")
set --
if [ -f "$__object/parameter/owner" ]; then
	owner=$(cat "$__object/parameter/owner")
	set -- "$@" "--owner $owner"
fi
if [ -f "$__object/parameter/group" ]; then
	group=$(cat "$__object/parameter/group")
	set -- "$@" "--group $group"
fi

## pass `--rsync-opts` as-is to `__rsync`:
if [ -f "$__object/parameter/rsync-opts" ]; then
	while read -r opts; do
		# shellcheck disable=SC2089
		set -- "$@" "--rsync-opts '$opts'"
	done < "$__object/parameter/rsync-opts"
fi

# shellcheck disable=SC2068,SC2090
__rsync /etc/xymon/ \
	--source "$__type/files/$confdir/" \
	--rsync-opts "delete" \
	$@
