#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage groups.
#

name="$__object_id"

cd "$__object/parameter"
if grep -q "^${name}:" "$__object/explorer/group"; then
   for property in $(ls .); do
      new_value="$(cat "$property")"

      case "$key" in
         password)
            current_value="$(awk -F: '{ print $2 }' < "$__object/explorer/gshadow")"
         ;;
         gid)
            current_value="$(awk -F: '{ print $3 }' < "$__object/explorer/group")"
         ;;
      esac

      if [ "$new_value" != "$current_value" ]; then
         set -- "$@" "--$property" \"$new_value\"
      fi
   done

   if [ $# -gt 0 ]; then
      echo groupmod "$@" "$name"
   else
      true
   fi
else
   for property in $(ls .); do
      new_value="$(cat "$property")"
      set -- "$@" "--$property" \"$new_value\"
   done

   echo groupadd "$@" "$name"
fi
