#!/bin/sh
#
if [ -f "$__object/parameter/repo_uri" ]; then
   uri="$(cat "$__object/parameter/repo_uri")"
else
   uri="/$__object_id"
fi
echo $(zypper lr -u | grep -E "\<$uri\>" | cut -d'|' -f 1 | grep -E '^[0-9]' )
