#!/bin/sh
#
# 2010-2011 Daniel Roth (dani-cdist@d-roth.li)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

if [ -f "$__object/parameter/file" ]; then
   file=$(cat "$__object/parameter/file")
else
   file="/$__object_id"
fi

result=$(cat "$__object/explorer/findline")

if [ "$result" = "NOTFOUND" ]; then
  line=$(cat "$__object/parameter/line")
  echo "echo \"$line\" >> $file"
fi
