#!/bin/sh
#
# 2013 Chase Allen James <nx-cdist@nu-ex.com>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

version="$__object_id"
state_is="$(cat "$__object/explorer/state")"
state_should="present"
[ -f "$__object/parameter/state" ] && state_should="$(cat "$__object/parameter/state")"

case "$state_is" in
  present)
    if [ "$state_should" = "absent" ]; then
      echo "rbenv uninstall $version"
      echo "rbenv rehash"
    fi
  ;;
  absent)
    if [ "$state_should" = "present" ]; then
      echo "rbenv install $version"
      echo "rbenv rehash"
    fi
  ;;
  *)
    echo "Unknown state: $state_should" >&2
    exit 1
  ;;
esac
