#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __file is a very basic type and should be able to be used as an
# example for typewrites later
#

type="$(cat parameters/type)"

# If destination was specified, do not use the id
if [ -f parameters/destination ]; then
   destination="$(cat parameters/destination)"
else
   destination="$1"
fi

case "$type" in
   directory)
      echo mkdir \"$destination\"
   ;;

   file)
      echo touch \"$destination\"
   ;;

   *)
      echo "Unsupported type: \"$type\"" >&2
      exit 1
   ;;
esac

if [ -f parameters/mode ]; then
   mode="$(cat parameters/mode)"
   echo chmod \"$mode\" \"$destination\"
fi
