#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __file is a very basic type, which will probably be reused quite often
#

destination="/$__object_id"
state_should="$(cat "$__object/parameter/state")"
exists="$(cat "$__object/explorer/exists")"

case "$state_should" in
   present)
      # No source? Create empty file
      if [ ! -f "$__object/parameter/source" ]; then
         if [ "$exists" = "no" ]; then
            echo touch \"$destination\"
         fi
      fi

      # Mode
      if [ -f "$__object/parameter/mode" ]; then
         cat << DONE
new=$(cat "$__object/parameter/mode")
old=\$(ls -l -- "$destination" | sed 's/.\(.........\).*/\1/
h;y/rwsxtST-/IIIIIOOO/;x;s/..\(.\)..\(.\)..\(.\)/|\1\2\3/
y/sStTx-/IIIIOO/;G
s/\n\(.*\)/\1;OOO0OOI1OIO2OII3IOO4IOI5IIO6III7/;:k
s/|\(...\)\(.*;.*\1\(.\)\)/\3|\2/;tk
s/^0*\(..*\)|.*/\1/;q')
# allow \$new to start with a 0 (when the sed expression above will not)
if [ \$(echo \$new | cut -c1) -eq 0 ]; then
   new=\$(echo \$new | cut -c2-)
fi
if [ \$new -ne \$old ]; then
   chmod \$new "$destination"
fi
DONE
      fi

      # Group
      if [ -f "$__object/parameter/group" ]; then
         cat << DONE
new=$(cat "$__object/parameter/group")
if echo \$new | grep -q "^[[:digit:]]\+$"; then
   # we were given a gid
   old=\$(ls -n "$destination" | awk '{print \$4}')
  else
   # we were given a group name
   old=\$(ls -l "$destination" | awk '{print \$4}')
fi
if [ "\$new" != "\$old" ]; then
   chgrp \$new "$destination"
fi
DONE
      fi

      # Owner
      if [ -f "$__object/parameter/owner" ]; then
         cat << DONE
new=$(cat "$__object/parameter/owner")
if echo \$new | grep -q "^[[:digit:]]\+$"; then
   # we were given a uid
   old=\$(ls -n "$destination" | awk '{print \$3}')
  else
   # we were given a user name
   old=\$(ls -l "$destination" | awk '{print \$3}')
fi
if [ "\$new" != "\$old" ]; then
   chown \$new "$destination"
fi
DONE
      fi
   ;;

   absent)
      if [ "$exists" = "yes" ]; then
         echo rm -f \"$destination\"
      fi

   ;;

   *)
      echo "Unknown state: $state_should" >&2
      exit 1
   ;;

esac
