#!/bin/sh
#
# 2013 Chase Allen James (nx-cdist@nu-ex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Check the status of a package
#
name="$__object_id"
[ -f "$__object/parameter/name" ] && name="$(cat "$__object/parameter/name")"

# Check if the package is installed via dpkg
if [ -n "$(dpkg -s "$name" 2>/dev/null | grep "^Status: install ok installed$")" ]; then
  echo present
else
  echo absent
fi
