#!/bin/sh
#
# 2015 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "$__global/explorer/os")

case "$os" in
   centos|redhat|ubuntu|debian|archlinux|gentoo)
      # any linux should work
      :
   ;;
   *)
      echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
      echo "Please contribute an implementation for it if you can." >&2
      exit 1
   ;;
esac


state="$(cat "$__object/parameter/state")"
install_from="$(cat "$__object/parameter/install-from")"
install_to="$(cat "$__object/parameter/install-to")"

if [ "$state" = "absent" ]; then
   __file "$install_to" \
      --state absent
   exit 0
fi

case "$install_from" in
   /*|file://*)
      source="${install_from#*file://}"
   ;;
   *.zip)
      mkdir "$__object/files"
      source="$__object/files/consul"
      # FIXME: need some persistent place to cache downloaded files
      curl -s "$install_from" | unzip -p > "$source"
   ;;
   *)
      echo "Do not know how to install from: $install_from" >&2
      exit 1
   ;;
esac

__file "$install_to" \
   --owner root --group root --mode 755 \
   --source "$source"
