#!/bin/sh
#
# 2015 Steven Armstrong (steven-cdist at armstrong.cc)
# 2016 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "$__global/explorer/os")

case "$os" in
   scientific|centos|redhat|ubuntu|debian|devuan|archlinux|gentoo)
      # any linux should work
      :
   ;;
   *)
      echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
      echo "Please contribute an implementation for it if you can." >&2
      exit 1
   ;;
esac

versions_dir="$__type/files/versions"
version="$(cat "$__object/parameter/version")"
version_dir="$versions_dir/$version"

if [ ! -d "$version_dir" ]; then
   echo "Unknown consul version '$version'. Expected one of:" >&2
   ls "$versions_dir" >&2
   exit 1
fi

__staged_file /usr/local/bin/consul \
   --source "$(cat "$version_dir/source")" \
   --cksum "$(cat "$version_dir/cksum")" \
   --fetch-command 'curl -s -L "%s"' \
   --prepare-command 'unzip -p "%s"' \
   --state "$(cat "$__object/parameter/state")" \
   --group root \
   --owner root \
   --mode 755
