#!/bin/sh
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

if [ -f "$__object/parameter/state" ]; then
    state_should="$(cat "$__object/parameter/state")"
else
    state_should="present"
fi

os=$(cat "$__global/explorer/os")
name="$__object_id"

# Support runlevels later
#runlevel=$(cat $__global/explorer/runlevel)

case "$state_should" in
    present)
        case "$os" in
            debian|ubuntu)
                echo update-rc.d \"$name\" defaults
            ;;

            gentoo)
                echo rc-update add \"$name\" default
            ;;

            centos|fedora|owl|redhat)
                echo echo chkconfig \"$name\" on
            ;;

            *)
               echo "Unsupported os: $os" >&2
               exit 1
            ;;
        esac
    ;;

    absent)

    ;;


    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
