#!/bin/sh
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

state_should="$(cat "$__object/parameter/state")"
state_is=$(cat "$__object/explorer/state")

# Nothing todo, go away
[ "$state_should" = "$state_is" ] && exit 0

os=$(cat "$__global/explorer/os")
name="$__object_id"

case "$state_should" in
    present)
        case "$os" in
            archlinux)
                echo sed -i /etc/rc.conf \'s/^\\(DAEMONS=.*\\))/\\1 $name)/\'
            ;;
            debian|ubuntu)
                # This does not work as expected:
                # insserv: warning: current start runlevel(s) (3 4 5) of script `postfix' overwrites defaults (2 3 4 5).
                #echo update-rc.d \"$name\" defaults
                echo update-rc.d \"$name\" defaults
            ;;

# Disabled until the explorer is checked
#            gentoo)
#                echo rc-update add \"$name\" default
#            ;;

            centos|fedora|owl|redhat)
                echo chkconfig \"$name\" on
            ;;

            *)
               echo "Unsupported os: $os" >&2
               exit 1
            ;;
        esac
    ;;

    absent)
        case "$os" in
            archlinux)
                echo sed -i /etc/rc.conf -e \"s/ $name / /g\" -e \"s/($name/(/\" -e \"s/ $name)/)/\"
            ;;
            debian|ubuntu)
                echo update-rc.d -f \"$name\" remove
            ;;

# Disabled until the explorer is checked
#            gentoo)
#                echo rc-update del \"$name\"
#            ;;

            centos|fedora|owl|redhat)
                echo chkconfig \"$name\" off
            ;;

            *)
               echo "Unsupported os: $os" >&2
               exit 1
            ;;
        esac
 
    ;;

    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
