#!/bin/sh -e
# -*- mode: sh; indent-tabs-mode: t -*-
#
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Returns the "context" of the configuration setting.
# cf. also https://www.postgresql.org/docs/10/view-pg-settings.html

os=$("${__explorer:?}/os")

case ${os}
in
	(openbsd)
		postgres_user='_postgresql'
		;;
	(devuan)
		postgres_user='postgres'
		;;
	(*)
		echo "Unsupported OS: ${os}" >&2
		exit 1
		;;
esac

conf_name=${__object_id:?}

su - "${postgres_user}" -c "psql postgres -twAc \"SELECT context FROM pg_settings WHERE name = '${conf_name}'\""
