#!/bin/sh -e
#
# 2016 Kamila Součková (coding at kamila.is)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage pf(4) on *BSD
#

rcvar="$(cat "${__object}/explorer/rcvar")"
state="$(cat "${__object}/parameter/state")"
if [ -f "${__object}/parameter/source" ]; then
    source="$(cat "${__object}/parameter/source")"
fi

if [ "${state}" = "absent" ]; then
    action="/etc/rc.d/pf stop"
else
    action="/etc/rc.d/pf reload || /etc/rc.d/pf start"
fi

__key_value __pf_ruleset/rcvar \
    --state "${state}" \
    --file /etc/rc.conf \
    --delimiter "=" \
    --key "pf_enable" \
    --value "YES"

require="__key_value/__pf_ruleset/rcvar" __config_file "${rcvar}" \
    --source "${source}" \
    --state "${state}" \
    --onchange "${action}"
