#!/bin/sh
#
# 2016 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "$__global/explorer/os")

case "$os" in
   centos)
      component="main"
      if [ -f "$__object/parameter/experimental" ]; then
         component="experimental"
      fi
      export CDIST_ORDER_DEPENDENCY=on
      __yum_repo docker \
         --name 'Docker Repository' \
         --baseurl "https://yum.dockerproject.org/repo/$component/centos/\$releasever/" \
         --enabled \
         --gpgcheck \
         --gpgkey 'https://yum.dockerproject.org/gpg'
      __package docker-engine
      unset CDIST_ORDER_DEPENDENCY
   ;;
   ubuntu)
      component="main"
      if [ -f "$__object/parameter/experimental" ]; then
         component="experimental"
      fi
      __package apparmor
      __package ca-certificates
      __package apt-transport-https
      __apt_key docker --keyid 58118E89F3A912897C070ADBF76221572C52609D
      export CDIST_ORDER_DEPENDENCY=on
      __apt_source docker \
         --uri https://apt.dockerproject.org/repo \
         --distribution "ubuntu-$(cat "$__global/explorer/lsb_codename")" \
         --component "$component"
      __package docker-engine
      unset CDIST_ORDER_DEPENDENCY
   ;;
   debian)
       component="main"
      if [ -f "$__object/parameter/experimental" ]; then
         component="experimental"
      fi

      __package apt-transport-https
      __package ca-certificates
      __package gnupg2
      __apt_key docker --keyid 58118E89F3A912897C070ADBF76221572C52609D
      export CDIST_ORDER_DEPENDENCY=on
      __apt_source docker \
          --uri https://apt.dockerproject.org/repo \
          --distribution "debian-$(cat "$__global/explorer/lsb_codename")" \
          --component "$component"
      __package docker-engine
      unset CDIST_ORDER_DEPENDENCY

   ;;
   *)
      echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
      echo "Please contribute an implementation for it if you can." >&2
      exit 1
   ;;
esac
