#!/bin/sh
function prepare() {
  #set -x
  if [ ! "$3" ]; then
    echo "We need a default value"
    exit 1
  fi

  if [ -f "$__object/parameter/$2" ]; then
    eval $1=`cat $__object/parameter/$2`
  else
    eval $1=$3
  fi
  #set +x
}


if [ no = "$(cat "$__object/explorer/kernel")" ]; then
  echo "Sorry this OS will not support LXC"
  exit 1
fi
# configure network (bridge, iptables masquerade ...)
# TODO: create a bridge type ...
# dependencies: bridge-utils
#__package bridge-utils --states installed
prepare "brname" "brname" "br0"
prepare "ifname" "ifname" "eth0"

__bridge $brname $ifname

# install lxc-tools
__package lxc --state installed

# send templates if some
if [ -d "$__type/templates" ] 
  require="__package/lxc" __directory /var/lib/lxc/conf
  for vm in `find $__type/templates  -maxdepth 1 -name '*.conf'`; do
    require="__directory/var/lib/lxc" __file /var/lib/lxc/conf/$vm --source $__type/templates/$vm
  done
fi
# set packages cache if asked

# send guests confs
