#!/bin/sh
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/name" ]; then
    name="$(cat "$__object/parameter/name")"
else
    name="$__target_host"
fi

os=$(cat "$__global/explorer/os")

echo "printf '%s\n' '$name' > /etc/hostname"

case "$os" in
   debian|ubuntu)
      echo "hostname \"$name\""
   ;;
   archlinux)
      echo "hostnamectl set-hostname \"$name\""
   ;;
esac
