#!/bin/sh -e
#
# 2012 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 Nico Schottelius (nico-cdist at schottelius.org)
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "$__global/explorer/os")
if [ -f "$__object/parameter/name" ]; then
    name_should="$(cat "$__object/parameter/name")"
else
    case "$os" in
    # RedHat-derivatives and BSDs
    centos|fedora|redhat|scientific|freebsd|netbsd|openbsd)
        # Hostname is FQDN
        name_should="${__target_host}"
    ;;
    *)
        # Hostname is only first component of FQDN
        name_should="${__target_host%%.*}"
    ;;
    esac
fi


not_supported() {
   echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
   echo "Please contribute an implementation for it if you can." >&2
   exit 1
}

case "$os" in
    archlinux|debian|suse|ubuntu|devuan|coreos|alpine|macosx)
        # handled in gencode-remote
        :
    ;;
    centos|fedora|redhat|scientific)
        __key_value sysconfig-hostname \
            --file /etc/sysconfig/network \
            --delimiter '=' --exact_delimiter \
            --key HOSTNAME \
            --value "\"$name_should\""
    ;;
    freebsd)
        __key_value rcconf-hostname \
            --file /etc/rc.conf \
            --delimiter '=' --exact_delimiter \
            --key 'hostname' \
            --value "$name_should"
    ;;
    netbsd)
        __key_value rcconf-hostname \
            --file /etc/rc.conf \
            --delimiter '=' --exact_delimiter \
            --key 'hostname' \
            --value "\"$name_should\""
        # To avoid confusion, ensure that the hostname is only stored once
        __file /etc/myname --state absent
    ;;
    openbsd)
        echo "$name_should" | __file /etc/myname --source -
    ;;
    *)
        # On other operating systems we fall back to hostnamectl if available…
        test -n "$(cat "$__object/explorer/has_hostnamectl")" || not_supported
    ;;
esac
