#!/bin/sh
#
# 2012 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "$__global/explorer/os")
if [ -f "$__object/parameter/name" ]; then
    name_should="$(cat "$__object/parameter/name")"
else
    case "$os" in
    openbsd)
        name_should="$(echo "${__target_host}")"
    ;;
    *)
        name_should="$(echo "${__target_host%%.*}")"
    ;;
    esac
fi


not_supported() {
   echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
   echo "Please contribute an implementation for it if you can." >&2
   exit 1
}

case "$os" in
    archlinux|debian|suse|ubuntu|devuan)
        # handled in gencode-remote
        :
    ;;
    scientific|centos)
        __key_value sysconfig-hostname \
            --file /etc/sysconfig/network \
            --delimiter '=' \
            --key HOSTNAME \
            --value "$name_should" --exact_delimiter
    ;;
    openbsd)
        echo "$name_should" | __file /etc/myname --source -
    ;;
    *)
        not_supported
    ;;
esac
