#!/bin/sh
#
# 2012 Evax Software <contact@evax.fr>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

gemset="$__object_id"
ruby="$(echo "$gemset" | cut -d '@' -f 1)"
gemsetname="$(echo "$gemset" | cut -d '@' -f 2)"
user="$(cat "$__object/parameter/user")"
state="$(cat "$__object/explorer/state")"
if [ -f "$__object/parameter/default" ]; then
   default="$(cat "$__object/parameter/default")"
else
   default="no"
   echo $default > "$__object/parameter/default"
fi

__rvm "$user" --state present
require="__rvm/$user" \
   __rvm_ruby $ruby --user "$user" --state present --default $default

