#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# BIG FAT FIXME: there must be a better way to do this!
tmpdir=$(mktemp -d)
cleanup() {
   rm -rf "$tmpdir"
}
trap cleanup EXIT

should="$tmpdir/should"
is="$tmpdir/is"

find "$__global/object/__apt_ppa" -path "*.cdist/parameter/state" | xargs cat > "$should"
find "$__global/object/__apt_ppa" -path "*.cdist/explorer/state" | xargs cat > "$is"

diff -ru "$is" "$should" || echo apt-get update

