#!/bin/sh
#
# 2011-2013 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __package is an abstract type which dispatches to the lower level
# __package_$type types which do the actual interaction with the packaging
# system.
#

type="$__object/parameter/type"
if [ -f "$type" ]; then
   type="$(cat "$type")"
else
   # By default determine package manager based on operating system
   os="$(cat "$__global/explorer/os")"
   case "$os" in
         amazon|scientific|centos|fedora|redhat) type="yum" ;;
         archlinux) type="pacman" ;;
         debian|ubuntu|devuan) type="apt" ;;
         freebsd)
            if [ -n "$(cat "$__object/explorer/pkgng_exists")" ]; then
               type="pkgng_freebsd"
            else
               type="pkg_freebsd"
            fi
            ;;
         gentoo) type="emerge" ;;
         suse) type="zypper" ;;
         openwrt) type="opkg" ;;
         openbsd) type="pkg_openbsd" ;;
         *)
            echo "Don't know how to manage packages on: $os" >&2
            exit 1
         ;;
   esac
fi

state="$(cat "$__object/parameter/state")"

set -- "$@" "$__object_id" "--state" "$state"
cd "$__object/parameter"
for property in $(ls .); do
   if [ "$property" != "type" -a "$property" != "state" ]; then
      set -- "$@" "--$property" "$(cat "$property")"
   fi
done

__package_$type "$@"
