#!/bin/sh
set -x

# add the machine to manifest
if  `grep "$guestname" $__type/../../manifest/init` ; then
  edit $__type/../../manifest/init << !
/esac
i
  $guestname)
  ;;
.
:x
!
fi


# if roles are defined 
## add it's roles to manifest
# send its configuration
