#!/bin/sh
#
# 2011-2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2013 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Mostly a wrapper for ln
#

destination="/$__object_id"

type="$(cat "$__object/parameter/type")"
source="$(cat "$__object/parameter/source")"

case "$type" in
    symbolic)
        lnopt="-s"
    ;;
    hard)
        lnopt=""
    ;;
    *)
        echo "Unknown link type: $type" >&2
        exit 1
    ;;
esac

state_is="$(cat "$__object/explorer/state")"
state_should="$(cat "$__object/parameter/state")"

[ "$state_should" = "$state_is" ] && exit 0

file_type="$(cat "$__object/explorer/type")"
case "$state_should" in
    present)
        if [ "$file_type" = "directory" ]; then
            # our destination is currently a directory, delete it
            cat << DONE
rm -rf "$destination"
DONE
        fi

        # create our link
        cat << DONE
ln ${lnopt} -f "$source" "$destination"
DONE
    ;;
    absent)
        # only delete if it is a sym/hard link
        if [ "$file_type" = "symlink" -o "$file_type" = "hardlink" ]; then
            echo rm -f \"$destination\"
        fi
    ;;
    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
