#!/bin/sh -e
#
# 2013 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

os=$(cat "$__global/explorer/os")

case "$os" in
    debian|ubuntu|devuan)

        # Debian and Ubuntu need to be updated,
        # as seen in /etc/init.d/bootlogs
        echo "uname -snrvm > /var/run/motd"
        echo "cat /etc/motd.tail >> /var/run/motd"
    ;;
    freebsd)
        # FreeBSD only updates /etc/motd on boot,
	# as seen in /etc/rc.d/motd
	echo "uname -sri > /etc/motd"
	echo "cat /etc/motd.template >> /etc/motd"
	# FreeBSD 13 starts treating motd slightly different from previous
	# versions this ensures hosts have the expected config.
	echo "rm /etc/motd.template || true"
	echo "service motd start"
    ;;
    *)
        # Other OS tend to treat /etc/motd statically
        exit 0
    ;;
esac
