#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

# Select motd source
if [ -f "$__object/parameter/source" ]; then
   source="$(cat "$__object/parameter/source")"
else
   source="$__type/files/motd"
fi

os=$(cat "$__global/explorer/os")


case "$os" in
   debian|ubuntu|devuan)
      destination=/etc/motd.tail
   ;;
   *)
      destination=/etc/motd
   ;;
esac

__file "$destination" --source "$source" --mode 0644
