#!/bin/sh -e
#
# 2019 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

path="/$__object_id"

[ ! -d "$path" ] && exit 0

pattern="$( cat "$__object/parameter/pattern" )"

if [ -f "$__object/parameter/exclude" ]
then
    exclude="$( cat "$__object/parameter/exclude" )"

    find "$path" -mindepth 1 -maxdepth 1 -regex "$pattern" \
        -and -not -regex "$exclude"
else
    find "$path" -mindepth 1 -maxdepth 1 -regex "$pattern"
fi
