#!/bin/sh
#
# 2013 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

base_dir=/etc/iptables.d

name="$__object_id"
state="$(cat "$__object/parameter/state")"

################################################################################
# Basic setup
#

__directory "$base_dir" --state present

# Have apply do the real job
require="$__object_name" __iptables_apply

################################################################################
# The rule
#

require="__directory/$base_dir" __file "$base_dir/${name}" \
    --source "$__object/parameter/rule" \
    --state "$state"
