#!/bin/sh
#
# 2012 Jake Guffey (jake.guffey at eprotex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# The __jail type creates, configures, and deletes FreeBSD jails for use as
#  virtual machines.
#

#FIXME: /usr/jail should never be hardcoded in this type
#FIXME: jailbase.tgz should not be hardcoded in this file

jailbase="/usr/jail/jailbase.tgz"
basepresent="$(cat "$__object/explorer/basepresent")"

if [ "$basepresent" = "NONE" ]; then
    __file "$jailbase" --source "$__object/files/jailbase.tgz"
fi

