#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

name="/$__object_id"
map="$(cat "$__object/parameter/map")"

if [ -f "$__object/parameter/type" ]; then
   type="$(cat "$__object/parameter/type")"
else
   type="file"
   echo "$type" > "$__object/parameter/type"
fi

# Generate entry for use in auto.master
entry="${name} ${type}:${map}"
if [ -f "$__object/parameter/options" ]; then
   entry="$entry $(cat "$__object/parameter/options")"
fi
if [ -f "$__object/parameter/comment" ]; then
   echo "# $(cat "$__object/parameter/comment")" > "$__object/parameter/entry"
fi
echo "$entry" >> "$__object/parameter/entry"

require="$__object_name" __autofs_master

