#!/bin/sh
#
# Copyright 2017, Philippe Gregoire <pg@pgregoire.xyz>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

#
# Retrieve the installurl(5), as introduced in OpenBSD 6.1
#
# As of 6.1, the file is supposed to contained a single line
# with the URL used to install from during install or upgrade.
#
# Allow for expansion and take the first non-commented (#) line.
#

if [ -f /etc/installurl ]; then
	printf 'yes'
else
	printf 'no'
fi

exit 0
