#!/bin/sh
#
# Copyright 2018, Takashi Yoshi <takashi@yoshi.email>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Retrieve the status of a package - parsed pkg_info output
#

if [ -f "${__object}/parameter/name" ]
then
	pkgid="$(cat "${__object}/parameter/name")"
else
	pkgid="${__object_id}"
fi

if [ -f "${__object}/parameter/version" ]
then
	pkgid="${pkgid}-$(cat "${__object}/parameter/version")"
fi

if [ -f "${__object}/parameter/flavor" ]
then
	# If a flavor but no version is given we need to add another -,
	# otherwise pkg_info confuses the flavor with the version.
	[ -f "${__object}/parameter/version" ] || pkgid="${pkgid}-"

	pkgid="${pkgid}-$(cat "${__object}/parameter/flavor")"
fi


pkg_info -q -I "inst:${pkgid}" >/dev/null 2>&1 \
	&& echo 'present' || echo 'absent'

exit 0
