#!/bin/sh

manager="$(cat "$__object/explorer/service-manager")"
name=$__object_id
action="$(cat "$__object/parameter/action")"

if [ "$manager" = "unknown" ]; then
	echo "service '$name' '$action'"
fi
