#!/bin/sh -e

path_is=$(
    LC_ALL=C update-alternatives --display "${__object_id?}" 2>/dev/null \
    | awk '/link currently points to/ { print $5 }')

if [ -z "$path_is" ] && [ -z "${__cdist_dry_run+dry run}" ]
then
    # NOTE: ignore error for dry-runs because a package providing the
    #       alternative might be managed by another cdist object (which
    #       wasn't executed, because dry run…).
    echo "unable to get current path for ${__object_id:?}" >&2
    exit 1
fi

echo "$path_is"
