#!/bin/sh
#
# 2011-2015 Steven Armstrong (steven-cdist at armstrong.cc)
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Get an existing groups gshadow entry.
#

name=$__object_id
os=$("$__explorer/os")

not_supported() {
	echo "Your operating system ($os) is currently not supported." >&2
	echo "Cannot extract group information." >&2
	echo "Please contribute an implementation for it if you can." >&2
	exit 1
}

case $os in
	"freebsd"|"netbsd")
		echo "$os does not have getent gshadow" >&2
		exit 0
	;;
esac

if command -v getent >/dev/null
then
	getent gshadow "$name" || true
elif [ -f /etc/gshadow ]
then
	grep "^${name}:" /etc/gshadow || true
else
	not_supported
fi
