#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

__package acpid --state installed
__package pm-utils --state installed

event_dir=/etc/acpi/events
event_file="$event_dir/lid"

action_dir=/etc/acpi/actions
action_file="$action_dir/lid.sh"

__directory "$event_dir" --owner root --group root \
   --mode 0755 --parents yes

__directory "$action_dir" --owner root --group root \
   --mode 0755 --parents yes

require="__directory/$event_dir" __file "$event_file" \
   --owner root --group root --mode 0644 \
   --source "$__type/files/lid_event"

require="__directory/$action_dir" __file "$action_file" \
   --owner root --group root --mode 0755 \
   --source "$__type/files/lid.sh"
