#!/bin/sh
#
# 2011 Aurélien Bondis (aurelien.bondis AT gmail DOT com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# USEFUL DESCRIPTION
#
# set documentroot value
# function to prepare variables regarding parameters
# takes variable's name, parameter's name and default value
function prepare() {
set -x
if [ ! "$3" ]; then
  echo "We need a default value"
  exit 1
fi

if [ -f "$__object/parameter/$2" ]; then
  eval $1=`cat $__object/parameter/$2`
else
  eval $1=$3
fi
set +x
}

prepare "root" "root" "/var/www/$__object_id"

if [ -f "$__object/parameter/template" ] && [ -f "$__object/parameter/source" ]; then
  echo "Please use either a source or a template"
  exit 1;
fi
#FIXME: need to find a place for full configurations
prepare "tpl" "template" "$__type/files/basic.tpl"
if [ ! -f "$tpl" ]; then
  echo "Missing template $tpl"
  exit 1
fi

prepare "servername" "servername" "$__object_id"
prepare "location" "location" "/"
prepare "index" "index" "index.php"

# copy the conf to tmp location
tmpconf="$__object/template-$__object_id"
cat $__type/files/header.tpl > $tmpconf
cat $tpl >> $tmpconf
# generate file if template is used
sed -i "s!\$SERVERNAME!$servername!g" $tmpconf
sed -i "s!\$ROOT!$root!g" $tmpconf
sed -i "s!\$LOCATION!$location!g" $tmpconf
sed -i "s!\$INDEX!$index!g" $tmpconf
sed -i "s!\$REPOROOT!$reporoot!g" $tmpconf
sed -i "s!\$REPO!$repo!g" $tmpconf
echo "}" >> $tmpconf

# send the file
require="__package/nginx" __directory /etc/nginx/sites-available
require="__directory/etc/nginx/sites-available" __file /etc/nginx/sites-available/$servername.conf --source $tmpconf


#
# This is the manifest, which can be used to create other objects like this:
# __file /path/to/destination --source /from/where/ --type file
#
# To tell cdist to make use of it, you need to make it executable (chmod +x)
#
#

