#!/bin/sh
#
# 2012 Jake Guffey (jake.guffey at eprotex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage pf(4) on *BSD
#

# Debug
#exec >&2
#set -x

state="$(cat "$__object/parameter/state")"

if [ -f "$__object/parameter/ruleset" ]; then
	ruleset="$(cat "$__object/parameter/ruleset")"
fi

if [ -f "$__object/parameter/testscript" ]; then
	testscript="$(cat "$__object/parameter/testscript")"
fi

rcvar="$(cat "$__object/explorer/rcvar")"
cksum="$(cat "$__object/explorer/cksum")"

cat <<EOF
exec >&2
set -x
# This file is used as a canary later, make sure we don't get a false positive
rm -f /tmp/test

if [ "$state" = "enabled" ]; then
	pfctl -e || true
else
	pfctl -d || true
	exit 0
fi

revert() {
	pfctl -f "${rcvar}"
	echo "Test(s) failed after applying new ruleset." >&2
	echo "Reverting back to previous ruleset." >&2
	exit 255
}

if [ -f "${rcvar}.new" ]; then
	pfctl -f "${rcvar}.new"
fi
if [ -f "${rcvar}.tests" ]; then
	sh ${rcvar}.tests
fi
if [ ! "\$?" -eq "0" ]; then	# error occurred
	revert
else	# test(s) succeeded
	sleep 20
	if [ ! -f /tmp/test ]; then	# Apparently the upstream cdist server can't get back to us
		revert
	else
		rm -f "${rcvar}" "${rcvar}.tests"
		mv "${rcvar}.new" "${rcvar}"
		exit 0
	fi
fi
set +x
EOF

# Debug
#set +x

