#!/bin/sh
#
# 2012 Jake Guffey (jake.guffey at eprotex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __build is an abstract type which dispatches to the lower level
# __build_$name types which do the actual interaction with the software
# build system.
#

if [ -f "$__object/parameter/name" ]; then
   name="$(cat "$__object/parameter/name")"
else
   name="$__object_id"
fi

if [ -f "$__object/parameter/type" ]; then
   type="$(cat "$__object/parameter/type")"
else
   type="port_freebsd"
fi

set -- "$@" "$__object_id"
cd "$__object/parameter"
for property in $(ls .); do
   if [ "$property" != "type" ]; then
      set -- "$@" "--$property" "$(cat "$property")"
   fi
done

__build_$type "$@"
