#!/bin/sh
#
# 2011,2013 Nico Schottelius (nico-cdist at schottelius.org)
# 2012 Giel van Schijndel (giel plus cdist at mortis dot eu)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage packages on OpenWRT and co.
#

if [ -f "$__object/parameter/name" ]; then
   name="$(cat "$__object/parameter/name")"
else
   name="$__object_id"
fi

state_should="$(cat "$__object/parameter/state")"

state_is="$(cat "$__object/explorer/pkg_status")"
case "$state_is" in
    absent*)
       present="$(echo "$state_is" | cut -d ' ' -f 2)"
       state_is="absent"
    ;;
esac

[ "$state_is" = "$state_should" ] && exit 0

case "$state_should" in
    present)
        if [ "$present" = "notpresent" ]; then
            echo opkg --verbosity=0 update
        fi
        echo opkg --verbosity=0 install \"$name\"
    ;;
    absent)
        echo opkg --verbosity=0 remove \"$name\"
    ;;
    *)
        echo "Unknown state: $state" >&2
        exit 1
    ;;
esac
