#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# shellcheck source=files/functions.sh
. "${__type:?}/files/functions.sh"


os=$(cat "${__global:?}/explorer/os")

state_is=$(cat "${__object:?}/explorer/state")
state_should=$(cat "${__object:?}/parameter/state")
transaction_name=$(cat "${__object:?}/parameter/transaction")

case ${os}
in
	(openwrt)
		# okay
		;;
	(*)
		printf "Your operating system (%s) is currently not supported by this type (%s)\n" "${os}" "${__type##*/}" >&2
		printf "Please contribute an implementation for it if you can.\n" >&2
		exit 1
		;;
esac

changes_required=false

case ${state_should}
in
	(present)
		test -s "${__object:?}/parameter/value" || {
			echo 'The parameter --value is required.' >&2
			exit 1
		}

		# NOTE: order is ignored so rearranged is also fine.
		in_list "${state_is}" 'present' 'rearranged' || changes_required=true
		;;
	(absent)
		in_list "${state_is}" 'absent' || changes_required=true
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac

if ${changes_required}
then
	# Make sure the changes are being committed
	require=${__object_name:?} __uci_commit "${transaction_name}"
fi
