#!/bin/sh -e
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


os=$(cat "${__global:?}/explorer/os")

case ${os}
in
	(ubuntu|debian|devuan)
		__file /etc/apt/apt.conf.d/00InstallRecommends --state present \
			--owner root --group root --mode 0644 --source - <<-'EOF'
		APT::Install-Recommends "false";
		APT::Install-Suggests "false";
		APT::AutoRemove::RecommendsImportant "false";
		APT::AutoRemove::SuggestsImportant "false";
		EOF

		# TODO: Remove the following object after some time
		require=__file/etc/apt/apt.conf.d/00InstallRecommends \
		__file /etc/apt/apt.conf.d/99-no-recommends --state absent
		;;
	(*)
		cat >&2 <<EOF
The developer of this type (${__type##*/}) did not think your operating system
($os) would have any use for it. If you think otherwise please submit a patch.
EOF
		exit 1
		;;
esac
