#!/bin/sh
#
# 2015 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

destination="/$__object_id"

os=$(cat "$__global/explorer/os")

case "$os" in
    archlinux)
        kernel=/boot/vmlinuz-linux
        initramfs=/boot/initramfs-linux-fallback.img
        required_pkg="cdrkit syslinux"
    ;;
    *)
        echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
        echo "Please contribute an implementation for it if you can." >&2
        exit 1
    ;;
esac

# Our root
__directory "$destination" \
    --mode 0755

for rootdir in boot bin etc lib; do
    require="__directory/$destination" __directory "$destination/$rootdir" \
        --mode 0755
done

require="__directory/$destination/etc" __cdistmarker \
    --destination "$destination/etc/cdist-configured"

for pkg in $required_pkg; do
    __package "$pkg" --state present
done

# Create full dependency chain, because we don't know which file depends on which package
export CDIST_ORDER_DEPENDENCY=1

require="__directory/$destination/boot" __file "$destination/boot/linux" \
    --source "$kernel" --mode 0644

require="__directory/$destination/boot" __file "$destination/boot/initramfs" \
    --source "$initramfs" --mode 0644

require="__directory/$destination/boot" __file "$destination/boot/syslinux.cfg" \


 PROMPT 1
 TIMEOUT 50
 DEFAULT arch
 
 LABEL arch
         LINUX ../vmlinuz-linux
         APPEND root=/dev/sda2 rw
         INITRD ../initramfs-linux.img
 
 LABEL archfallback
         LINUX ../vmlinuz-linux
         APPEND root=/dev/sda2 rw
         INITRD ../initramfs-linux-fallback.img
