#!/bin/sh
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

path="$(cat "$__object/parameter/path" 2>/dev/null || echo "/$__object_id")"
state="$(cat "$__object/parameter/state")"

if [ ! -f "$__object/parameter/nofstab" ]; then
   # Generate an entry for /etc/fstab
   (
printf "%s" "$(cat "$__object/parameter/device")"
printf " %s" "$path"
type="$(cat "$__object/parameter/type")"
printf " %s" "$type"
options="$(cat "$__object/parameter/options")"
printf " %s" "$options"
printf " %s" "$(cat "$__object/parameter/dump")"
printf " %s\n" "$(cat "$__object/parameter/pass")"
) | \
__block "$__object_name" \
   --file "/etc/fstab" \
   --prefix "#cdist:$__object_name" \
   --suffix "#/cdist:$__object_name" \
   --state "$state" \
   --text -
fi
