#!/bin/sh -e
#
# 2018 Ľubomír Kučera <lubomir.kucera.jr at gmail.com>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

state=$(cat "${__object:?}/parameter/state")
swarm_state="$(cat "${__object}/explorer/swarm-state")"

if [ -z "${swarm_state}" ]; then
    echo "Unable to determine Swarm state. Is compatible version of Docker installed?" >&2

    exit 1
fi

case "${state}" in
    absent)
        if [ "${swarm_state}" = "active" ]; then
            echo "docker swarm leave --force"
        fi
    ;;
    present)
        if [ "${swarm_state}" = "inactive" ]; then
            echo "docker swarm init"
        fi
    ;;
    *)
        echo "Unsupported state: ${state}" >&2

        exit 1
    ;;
esac
