#!/bin/sh -e

files="bin/cdist-config doc/changelog"

# Stuff to take care of when doing a release
echo "Preparing next release"

# Ensure documentation builds cleanly
./build.sh clean && ./build.sh man

# get version
version=$(awk -F'=' '/^__cdist_version/ { print $2 }' bin/cdist-config | sed 's/"//g')

# get target branch
branch=${version%.?}

# adjust version and release date
vi $files

# Commit stuff
git commit $files

# add tag
printf "Enter description for %s>" "$version"
read tagmessage
git tag "$version" "$tagmessage"

# Import into current version branch
git checkout $branch
git merge master
git checkout master

# Publish manpages and sourcecode
./build.sh web
./build.sh pub
