#!/bin/sh
#
# 2011 Ramon Salvadó (rsalvado at gnuine dot com)
# 2012-2015 Steven Armstrong (steven-cdist at armstrong.cc)
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# This type allows to configure the desired localtime timezone.

timezone="$__object_id"
os=$(cat "$__global/explorer/os")

case "$os" in
    archlinux|debian|ubuntu|devuan)
        __package tzdata
        export require="__package/tzdata"
    ;;
    suse)
        __package timezone
        export require="__package/timezone"
    ;;
    freebsd|netbsd)
        # whitelist
        :
    ;;
    scientific|centos)
        __package tzdata --state present
        export require="__package/tzdata"
        __file /etc/sysconfig/clock \
            --owner root --group root --mode 644 \
            --state exists
        require="__file/etc/sysconfig/clock" \
            __key_value ZONE \
                --file /etc/sysconfig/clock \
                --delimiter '=' \
                --value "\"$timezone\""
    ;;
    *)
        echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
        echo "Please contribute an implementation for it if you can." >&2
        exit 1
    ;;
esac

__link /etc/localtime \
    --source "/usr/share/zoneinfo/${timezone}" \
    --type symbolic
