#!/bin/sh
#
# 2012 Sébastien Gross <seb•ɑƬ•chezwam•ɖɵʈ•org>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# List all network interfaces in explorer/ifaces. One interface per line.
#

uname_s="$(uname -s)"

case "$uname_s" in
   Linux)
      ifconfig  | sed -n 's/^\([^[:space:]]\+\)[[:space:]].*/\1/p' 
      exit 0
   ;;
   Darwin|*BSD)
      ifconfig | sed -n 's/^\([^:]*\): flags.*/\1/p'
      exit 0
   ;;
esac

echo "Unknown OS" >&2
exit 1
