#!/bin/sh
#
# 2010-2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# All os variables are lower case
#
#

# Ubuntu is also Debian, thus return if Ubuntu was found
if grep -q ^DISTRIB_ID=Ubuntu /etc/lsb-release 2>/dev/null; then
   echo ubuntu
   exit 0
fi

if [ -f /etc/arch-release ]; then
   echo archlinux
   exit 0
fi

if [ -f /etc/debian_version ]; then
   echo debian
   exit 0
fi

if [ -f /etc/gentoo-release ]; then
   echo gentoo
   exit 0
fi

if [ -f /etc/redhat-release ]; then
   echo redhat
   exit 0
fi

if [ -f /etc/SuSE-release ]; then
   echo suse
   exit 0
fi

case "$(uname -s)" in
   Darwin)
      echo macosx
      exit 0
   ;;
esac

echo "Unknown OS" >&2
exit 1
