#!/bin/sh

trigger_command=$(cat "$__object/parameter/trigger-command")

__file /etc/systemd/system/cdist-preos-trigger.service --owner root \
    --group root \
    --mode 644 \
    --source - << EOF
[Unit]
Description=preos trigger
Wants=network-online.target
After=network.target network-online.target

[Service]
Type=simple
Restart=no
# Broken systemd
ExecStartPre=/bin/sleep 5
ExecStart=${trigger_command}

[Install]
WantedBy=multi-user.target
EOF

require="__file/etc/systemd/system/cdist-preos-trigger.service" \
    __start_on_boot cdist-preos-trigger
