#!/bin/sh
#
# 2012 Evax Software <contact@evax.fr>
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

user="$__object_id"

# RVM behaves differently if root is the username / uid == 0
if [ "$user" = "root" ]; then
    if [ -d /usr/local/rvm ]; then
        echo present
    else
        echo absent
    fi
else
    if su - $user -c "[ -d \"\$HOME/.rvm\" ]" ; then
       echo "present"
    else
       echo "absent"
    fi
fi
