#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Push a directory to a target, both sides have the same name (i.e. explorers)
# or
# Pull a directory from a target, both sides have the same name (i.e. explorers)
#


__cdist_dir()
{
   [ $# -eq 3 ] || __cdist_usage "<push|pull> <src dir> <dst dir>"

   __cdist_dir_action="$1"; shift
   __cdist_dir_src="$1"; shift
   __cdist_dir_dst="$1"; shift

   # This will be the destination directory, so no subdirectories
   # of the same name are created, if the directory is already existing
   __cdist_dir_top="${__cdist_dir_dst%/*}"

   if [ "$__cdist_dir_action" = "push" ]; then
      ssh "${__cdist_remote_user}@${__cdist_target_host}" \
         "mkdir -p \"${__cdist_dir_dst}\""
      scp -qr "$__cdist_dir_src" \
         "${__cdist_remote_user}@${__cdist_target_host}:${__cdist_dir_top}"
   elif [ "$__cdist_dir_action" = "pull" ]; then
      mkdir -p "${__cdist_dir_dst}"
      scp -qr "${__cdist_remote_user}@${__cdist_target_host}:${__cdist_dir_src}" \
         "${__cdist_dir_top}"
   else
      __cdist_exit_err "Unknown action $__cdist_dir_action"
   fi
}
