#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# echo / syslog alike function
#

__cdist_echo()
{
   __cdist_echo_type="$1"; shift

   set +u
   if [ "$__cdist_object_self" ]; then
      __cdist_echo_prefix="${__cdist_object_self}:"
   else
      __cdist_echo_prefix="core: "
   fi
   set -u

   case "$__cdist_echo_type" in
      debug)
         set +u
         if [ "$__cdist_debug" ]; then
            echo $__cdist_echo_prefix "Debug: $@"
         fi
         set -u
      ;;
      info)
         echo $__cdist_echo_prefix "$@"
      ;;
      warn)
         echo $__cdist_echo_prefix "Warning: $@"
      ;;
      error)
         echo $__cdist_echo_prefix "Error: $@" >&2
      ;;
      *)
         echo "CORE BUG, who created the broken commit in $0?" >&2
         exit 23
      ;;
   esac
}
