#!/bin/sh
#
# 2010-2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Copy & run the global explorers, i.e. not bound to types
#

__cdist_explorer_run_global()
{
   __cdist_echo info "Running global explorers "

   # run the global explorers remotely
   __cdist_explorer_run global \
      "$__cdist_explorer_dir" "$__cdist_remote_explorer_dir" \
      "$__cdist_remote_out_explorer_dir" "$__cdist_out_explorer_dir"
}
