#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Exit if an error occurs when running a shell script
#

__cdist_run_shell()
{
   set +e
   # Prepend our path, so all cdist tools come before other tools
   PATH="${__cdist_out_type_bin_dir}:$PATH" sh -e "$@"
   if [ "$?" -ne 0 ]; then
      __cdist_echo error  "$1 exited non-zero"
      __cdist_echo warn "Faulty code:"
      cat "$1"
      __cdist_exit_err "Aborting due to non-zero exit code."
   fi  
   set -e
}
