#!/bin/sh
#
# 2010 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# 
# Save the configuration tree into the local cache
#

__cdist_cache()
{
   # Create base to move into
   mkdir -p "${__cdist_local_base_cache_dir}"

   __cdist_echo info \
      "Saving cache to $(__cdist_host_cache_dir "$__cdist_target_host")"
   rm -rf "$(__cdist_host_cache_dir "$__cdist_target_host")"
   mv "$__cdist_local_base_dir" \
      "$(__cdist_host_cache_dir "$__cdist_target_host")"
}
