#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# 
# Run the given command for each created object.
#

__cdist_object_all()
{
   [ $# -eq 1 ] || __cdist_usage "<command>"

   __cdist_object_all_object_all_command="$1"; shift

   __cdist_object_all_object_all_objects="$__cdist_tmp_dir/objects"

   # Ensure object dir exists, so marker can be created
   mkdir -p "${__cdist_out_object_dir}"

   # FIXME: : - why do we use a file?
   #    core/__cdist_object_manifest_run:         touch "$__cdist_objects_created"

   # Loop until we do not create new objects anymore
   # which is equal to all objects have been run
   touch "$__cdist_objects_created"
   while [ -f "$__cdist_objects_created" ]; do
      # Assume we're done after this run
      rm "$__cdist_objects_created"

      # Get listing of objects
      __cdist_object_list "$__cdist_out_object_dir" > \
         "$__cdist_object_all_object_all_objects"

      # NEED TO CREATE ARRAY, SSH DESTROYS WHILE READ LOOP
      while read __cdist_object_all_object; do
         set -- "$@" "$__cdist_object_all_object"
      done < "$__cdist_object_all_object_all_objects"

      while [ $# -gt 0 ]; do
         __cdist_object_all_object="$1"; shift
         $__cdist_object_all_object_all_command "$__cdist_object_all_object"
      done
   done
}
