#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Prepare deployment
#

__cdist_init_deploy()
{
   __cdist_echo info "Creating clean directory structure "

   # Ensure there is no old stuff, neither local nor remote
   rm -rf "$__cdist_local_base_dir"
   ssh "${__cdist_remote_user}@${__cdist_target_host}" \
      "rm -rf ${__cdist_remote_base_dir}"

   # Init base
   mkdir -p "$__cdist_local_base_dir"
   ssh "${__cdist_remote_user}@${__cdist_target_host}" \
      "mkdir -p ${__cdist_remote_base_dir}"

   # Link configuration source directory - consistent with remote
   ln -sf "$__cdist_conf_dir" "$__cdist_local_base_dir/$__cdist_name_conf_dir"
}
