#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Exec the code for the given object locally and remote
#

__cdist_run_if_executable()
{
   [ $# -gt 1 ] || __cdist_exit_err "<executable> <command> <args>"

   __cdist_run_if_executable_exec="$1"; shift

   if [ -e "$__cdist_run_if_executable_exec" ]; then
      if [ -f "$__cdist_run_if_executable_exec" ]; then
         if [ -x "$__cdist_run_if_executable_exec" ]; then
            __cdist_echo debug "Running $@ ..."
            "$@"
         else
            __cdist_exit_err "$__cdist_run_if_executable_exec exists, but is not executable."
         fi
      else
         __cdist_exit_err "$__cdist_run_if_executable_exec exists, but is not a file."
      fi
   fi

   # Exit gracefully if nothing is todo
   true
}
