#!/bin/sh
prepare() {
#set -x
if [ ! "$3" ]; then
  echo "We need a default value"
  exit 1
fi

if [ -f "$__object/parameter/$2" ]; then
  eval $1=`cat $__object/parameter/$2`
else
  eval $1=$3
fi
#set +x
}

prepare "state" "state" "on"

if [ -f "$__object/parameter/srvlist" ]; then
  srvlist=`cat $__object/parameter/srvlist`
else
  echo we need a service list to enable/disable
  exit 1
fi

echo "
for i in $srvlist; do
  chkconfig \$i $state
done
"
