#!/bin/sh
#
# 2016 Dominique Roux (dominique.roux at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# Variables
version="$(cat "$__object/parameter/version")"
state="$(cat "$__object/parameter/state")"

if [ ${state} = "present" ]; then
    # Download docker-compose file
        echo 'curl -L "https://github.com/docker/compose/releases/download/'${version}'/docker-compose-$(uname -s)-$(uname -m)" -o /tmp/docker-compose'
        echo 'mv /tmp/docker-compose /usr/local/bin/docker-compose'
    # Change permissions
    echo 'chmod +x /usr/local/bin/docker-compose'
fi
