#!/bin/sh
#
# 2016 Dominique Roux (dominique.roux at ungleich.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

state="$(cat "$__object/parameter/state")"

# Needed packages
if [ ${state} = "present" ]; then
    __docker
    __package curl
elif [ ${state} = "absent" ]; then
    __file /usr/local/bin/docker-compose --state absent
else
    echo "Unknown state: ${state}" >&2
    exit 1
fi
