#!/bin/sh -e

state_is="$( cat "$__object/explorer/state" )"

state_should="$( cat "$__object/parameter/state" )"

if [ "$state_is" = "$state_should" ]
then
    exit 0
fi

privileges="$( cat "$__object/parameter/privileges" )"

database="$( cat "$__object/parameter/database" )"

table="$( cat "$__object/parameter/table" )"

user="$( cat "$__object/parameter/user" )"

host="$( cat "$__object/parameter/host" )"

case "$state_should" in
    present)
        echo "mysql -e 'grant $privileges on \`$database\`.\`$table\` to \`$user\`@\`$host\`'"
        echo "grant $privileges on $database.$table to $user@$host" >> "$__messages_out"
    ;;
    absent)
        echo "mysql -e 'revoke $privileges on \`$database\`.\`$table\` from \`$user\`@\`$host\`'"
        echo "revoke $privileges on $database.$table from $user@$host" >> "$__messages_out"
    ;;
esac
