#!/bin/sh -e
#
# 2017 Daniel Tschada (mail--at--moep.name)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

os=$(cat "$__global/explorer/os")
os_version=$(cat "$__global/explorer/os_version")
lsb_id=$(cat "$__global/explorer/lsb_id")

grub_default_path="/etc/default/grub"
# check os
case "$os" in
    devuan)
        case "$os_version" in
            jessie) GRUB_DISTRIBUTOR="$lsb_id"
                
                ;;
            ascii) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            *)  
                echo "Unsupported version: $os_version" >&2
                exit 1
                ;;
        esac
        ;;
    debian)
	case "$os_version" in
            6*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            7*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            8*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            9*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
	   10*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            *)  
                echo "Unsupported version: $os_version" >&2
                exit 1
                ;;
        esac
        ;;
    ubuntu)
	case "$os_version" in
            14*) GRUB_DISTRIBUTOR="$lsb_id"
                
                ;;
            15*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            16*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            17*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            18*) GRUB_DISTRIBUTOR="$lsb_id"

                ;;
            *)  
                echo "Unsupported version: $os_version" >&2
                exit 1
                ;;
        esac
        ;;
    *)  
        echo "Unsupported os: $os" >&2
        exit 1
        ;;
esac
# all parameter
[ -f "$__object/parameter/GRUB_DEFAULT" ] && GRUB_DEFAULT=$(cat "$__object/parameter/GRUB_DEFAULT")
[ -f "$__object/parameter/GRUB_TIMEOUT" ] && GRUB_TIMEOUT=$(cat "$__object/parameter/GRUB_TIMEOUT")
[ -f "$__object/parameter/GRUB_DISTRIBUTOR" ] && GRUB_TIMEOUT=$(cat "$__object/parameter/GRUB_DISTRIBUTOR")
[ -f "$__object/parameter/GRUB_CMDLINE_LINUX_DEFAULT" ] && GRUB_CMDLINE_LINUX_DEFAULT=$(cat "$__object/parameter/GRUB_CMDLINE_LINUX_DEFAULT")
[ -f "$__object/parameter/GRUB_CMDLINE_LINUX" ] && GRUB_CMDLINE_LINUX=$(cat "$__object/parameter/GRUB_CMDLINE_LINUX")
[ -f "$__object/parameter/GRUB_CMDLINE_NETBSD" ] && GRUB_CMDLINE_NETBSD=$(cat "$__object/parameter/GRUB_CMDLINE_NETBSD")
[ -f "$__object/parameter/GRUB_CMDLINE_NETBSD_DEFAULT" ] && GRUB_CMDLINE_NETBSD_DEFAULT=$(cat "$__object/parameter/GRUB_CMDLINE_NETBSD_DEFAULT")
[ -f "$__object/parameter/GRUB_CMDLINE_GNUMACH" ] && GRUB_CMDLINE_GNUMACH=$(cat "$__object/parameter/GRUB_CMDLINE_GNUMACH")
[ -f "$__object/parameter/GRUB_CMDLINE_XEN" ] && GRUB_CMDLINE_XEN=$(cat "$__object/parameter/GRUB_CMDLINE_XEN")
[ -f "$__object/parameter/GRUB_CMDLINE_XEN_DEFAULT" ] && GRUB_CMDLINE_XEN_DEFAULT=$(cat "$__object/parameter/GRUB_CMDLINE_XEN_DEFAULT")
[ -f "$__object/parameter/GRUB_CMDLINE_XEN_REPLACE" ] && GRUB_CMDLINE_LINUX_XEN_REPLACE=$(cat "$__object/parameter/GRUB_CMDLINE_LINUX_XEN_REPLACE")
[ -f "$__object/parameter/GRUB_CMDLINE_XEN_REPLACE_DEFAULT" ] && GRUB_CMDLINE_LINUX_XEN_REPLACE_DEFAULT=$(cat "$__object/parameter/GRUB_CMDLINE_LINUX_XEN_REPLACE_DEFAULT")
[ -f "$__object/parameter/GRUB_BADRAM" ] && GRUB_BADRAM=$(cat "$__object/parameter/GRUB_BADRAM")
[ -f "$__object/parameter/GRUB_SAVEDEFAULT" ] && GRUB_SAVEDEFAULT=$(cat "$__object/parameter/GRUB_SAVEDEFAULT")
[ -f "$__object/parameter/GRUB_TERMINAL" ] && GRUB_TERMINAL=$(cat "$__object/parameter/GRUB_TERMINAL")
[ -f "$__object/parameter/GRUB_TIMEOUT_STYLE" ] && GRUB_TIMEOUT_STYLE=$(cat "$__object/parameter/GRUB_TIMEOUT_STYLE")
[ -f "$__object/parameter/GRUB_GFXMODE" ] && GRUB_GFXMODE=$(cat "$__object/parameter/GRUB_GFXMODE")
[ -f "$__object/parameter/GRUB_INIT_TUNE" ] && GRUB_INIT_TUNE=$(cat "$__object/parameter/GRUB_INIT_TUNE")
[ -f "$__object/parameter/GRUB_DEFAULT_BUTTON" ] && GRUB_DEFAULT_BUTTON=$(cat "$__object/parameter/GRUB_DEFAULT_BUTTON")
[ -f "$__object/parameter/GRUB_TIMEOUT_BUTTON" ] && GRUB_TIMEOUT_BUTTON=$(cat "$__object/parameter/GRUB_TIMEOUT_BUTTON")
[ -f "$__object/parameter/GRUB_TIMEOUT_STYLE_BUTTON" ] && GRUB_TIMEOUT_STYLE_BUTTON=$(cat "$__object/parameter/GRUB_TIMEOUT_STYLE_BUTTON")
[ -f "$__object/parameter/GRUB_BUTTON_CMOS_ADDRESS" ] && GRUB_BUTTON_CMOS_ADDRESS=$(cat "$__object/parameter/GRUB_BUTTON_CMOS_ADDRESS")
[ -f "$__object/parameter/GRUB_TERMINAL_INPUT" ] && GRUB_TERMINAL_INPUT=$(cat "$__object/parameter/GRUB_TERMINAL_INPUT")
[ -f "$__object/parameter/GRUB_TERMINAL_OUTPUT" ] && GRUB_TERMINAL_OUTPUT=$(cat "$__object/parameter/GRUB_TERMINAL_OUTPUT")
[ -f "$__object/parameter/GRUB_SERIAL_COMMAND" ] && GRUB_SERIAL_COMMAND=$(cat "$__object/parameter/GRUB_SERIAL_COMMAND")
[ -f "$__object/parameter/GRUB_DISABLE_LINUX_UUID" ] && GRUB_DISABLE_LINUX_UUID=$(cat "$__object/parameter/GRUB_DISABLE_LINUX_UUID")
[ -f "$__object/parameter/GRUB_DISABLE_RECOVERY" ] && GRUB_DISABLE_RECOVERY=$(cat "$__object/parameter/GRUB_DISABLE_RECOVERY")
[ -f "$__object/parameter/GRUB_VIDEO_BACKEND" ] && GRUB_VIDEO_BACKEND=$(cat "$__object/parameter/GRUB_VIDEO_BACKEND")
[ -f "$__object/parameter/GRUB_BACKGROUND" ] && GRUB_BACKGROUND=$(cat "$__object/parameter/GRUB_BACKGROUND")
[ -f "$__object/parameter/GRUB_THEME" ] && GRUB_THEME=$(cat "$__object/parameter/GRUB_THEME")
[ -f "$__object/parameter/GRUB_GFXPAYLOAD_LINUX" ] && GRUB_GFXPAYLOAD_LINUX=$(cat "$__object/parameter/GRUB_GFXPAYLOAD_LINUX")
[ -f "$__object/parameter/GRUB_DISABLE_OS_PROBER" ] && GRUB_DISABLE_OS_PROBER=$(cat "$__object/parameter/GRUB_DISABLE_OS_PROBER")
[ -f "$__object/parameter/GRUB_OS_PROBER_SKIP_LIST" ] && GRUB_OS_PROBER_SKIP_LIST=$(cat "$__object/parameter/GRUB_OS_PROBER_SKIP_LIST")
[ -f "$__object/parameter/GRUB_DISABLE_SUBMENU" ] && GRUB_DISABLE_SUBMENU=$(cat "$__object/parameter/GRUB_DISABLE_SUBMENU")
[ -f "$__object/parameter/GRUB_ENABLE_CRYPTODISK" ] && GRUB_ENABLE_CRYPTODISK=$(cat "$__object/parameter/GRUB_ENABLE_CRYPTODISK")
[ -f "$__object/parameter/GRUB_PRELOAD_MODULES" ] && GRUB_PRELOAD_MODULES=$(cat "$__object/parameter/GRUB_PRELOAD_MODULES")
[ -f "$__object/parameter/GRUB_RECORDFAIL_TIMEOUT" ] && GRUB_RECORDFAIL_TIMEOUT=$(cat "$__object/parameter/GRUB_RECORDFAIL_TIMEOUT")
[ -f "$__object/parameter/GRUB_RECOVERY_TITLE" ] && GRUB_RECOVERY_TITLE=$(cat "$__object/parameter/GRUB_RECOVERY_TITLE")
[ -f "$__object/parameter/GRUB_HIDDEN_TIMEOUT" ] && GRUB_HIDDEN_TIMEOUT=$(cat "$__object/parameter/GRUB_HIDDEN_TIMEOUT")
[ -f "$__object/parameter/GRUB_HIDDEN_TIMEOUT_QUIET" ] && GRUB_HIDDEN_TIMEOUT_QUIET=$(cat "$__object/parameter/GRUB_HIDDEN_TIMEOUT_QUIET")
[ -f "$__object/parameter/GRUB_HIDDEN_TIMEOUT_BUTTON" ] && GRUB_HIDDEN_TIMEOUT_BUTTON=$(cat "$__object/parameter/GRUB_HIDDEN_TIMEOUT_BUTTON")

__file "$grub_default_path" \
    --source "$__type/files/grub" \
    --owner root --mode 0644

for var in GRUB_DEFAULT \
	   GRUB_TIMEOUT \
	   GRUB_DISTRIBUTOR \
	   GRUB_CMDLINE_LINUX_DEFAULT \
	   GRUB_CMDLINE_LINUX \
	   GRUB_CMDLINE_NETBSD \
	   GRUB_CMDLINE_NETBSD_DEFAULT \
	   GRUB_CMDLINE_GNUMACH \
	   GRUB_CMDLINE_XEN \
	   GRUB_CMDLINE_XEN_DEFAULT \
	   GRUB_CMDLINE_LINUX_XEN_REPLACE \
	   GRUB_CMDLINE_LINUX_XEN_REPLACE_DEFAULT \
	   GRUB_BADRAM \
	   GRUB_SAVEDEFAULT \
	   GRUB_TERMINAL \
	   GRUB_TIMEOUT_STYLE \
	   GRUB_GFXMODE \
	   GRUB_DISABLE_LINUX_UUID  \
	   GRUB_DISABLE_RECOVERY \
	   GRUB_INIT_TUNE \
	   GRUB_DEFAULT_BUTTON \
	   GRUB_TIMEOUT_BUTTON \
	   GRUB_TIMEOUT_STYLE_BUTTON \
	   GRUB_BUTTON_CMOS_ADDRESS \
	   GRUB_TERMINAL_INPUT \
	   GRUB_TERMINAL_OUTPUT \
	   GRUB_SERIAL_COMMAND \
	   GRUB_VIDEO_BACKEND \
	   GRUB_BACKGROUND \
	   GRUB_THEME \
	   GRUB_GFXPAYLOAD_LINUX \
	   GRUB_DISABLE_OS_PROBER \
	   GRUB_OS_PROBER_SKIP_LIST \
	   GRUB_DISABLE_SUBMENU \
	   GRUB_ENABLE_CRYPTODISK \
	   GRUB_PRELOAD_MODULES \
	   GRUB_RECORDFAIL_TIMEOUT \
	   GRUB_RECOVERY_TITLE \
	   GRUB_HIDDEN_TIMEOUT \
	   GRUB_HIDDEN_TIMEOUT_QUIET \
	   GRUB_HIDDEN_TIMEOUT_BUTTON; do
    eval "var_val=\$$var"  # get a value from variable which var is referencing
    if [ -n "${var_val}" ]; then
        require="__file/$grub_default_path"  __line $var \
            --file "$grub_default_path" --line $var=\""${var_val}"\" \
            --state present
    fi
done
