#!/bin/sh -e
#
# 2019 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# TODO check if filesystem has ACL turned on etc

if [ -f "$__object/parameter/acl" ]
then
    grep -E '^(default:)?(user|group):' "$__object/parameter/acl" \
    | while read -r acl
    do
        param="$( echo "$acl" | awk -F: '{print $(NF-2)}' )"
        check="$( echo "$acl" | awk -F: '{print $(NF-1)}' )"

        [ "$param" = 'user' ] && db=passwd || db="$param"

        if ! getent "$db" "$check" > /dev/null
        then
            echo "missing $param '$check'" >&2
            exit 1
        fi
    done
fi
