#!/bin/sh -e
#
# 2019 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

[ ! -e "/$__object_id" ] && exit 0

for parameter in user group
do
    if [ ! -f "$__object/parameter/$parameter" ]
    then
        continue
    fi

    while read -r acl
    do
        check="$( echo "$acl" | awk -F: '{print $1}' )"

        if [ "$parameter" = 'user' ]
        then
            getent_db=passwd
        else
            getent_db="$parameter"
        fi

        if ! getent "$getent_db" "$check" > /dev/null
        then
            echo "missing $parameter '$check'"
        fi
    done \
        < "$__object/parameter/$parameter"
done
