#!/bin/sh -e
#
# 2019 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

[ ! -s "$__object/explorer/list" ] && exit 0

path="/$__object_id"

pattern="$( cat "$__object/parameter/pattern" )"

if [ -f "$__object/parameter/exclude" ]
then
    exclude="$( cat "$__object/parameter/exclude" )"

    echo "find '$path' -mindepth 1 -maxdepth 1 -regex '$pattern'" \
        "-and -not -regex '$exclude'" \
        '-exec rm -rf {} \;'
else
    echo "find '$path' -mindepth 1 -maxdepth 1 -regex '$pattern'" \
        '-exec rm -rf {} \;'
fi

while read -r f
do
    echo "removed '$f'" >> "$__messages_out"
done \
< "$__object/explorer/list"

if [ -f "$__object/parameter/onchange" ]
then
    cat "$__object/parameter/onchange"
fi
