#!/bin/sh -e
#
# 2019 Ander Punnar (ander-at-kvlt-dot-ee)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

[ ! -f "$__object/explorer/list" ] && exit 0

for l in $( cat "$__object/explorer/list" )
do
    if echo "$l" | grep -Eq '/$'
    then
        __directory "$l" --state absent
        echo "removed directory '$l'" >> "$__messages_out"
    else
        __file "$l" --state absent
        echo "removed file '$l'" >> "$__messages_out"
    fi
done
