#!/bin/sh
#
# 2014 Ricardo Catalinas Jiménez (jimenezrick at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Upgrade all the already installed packages with the appropriate package
# manager
#

type="$__object/parameter/type"

if [ -f "$type" ]; then
    type="$(cat "$type")"
else
    # By default determine package manager based on operating system
    os="$(cat "$__global/explorer/os")"
    case "$os" in
        amazon|scientific|centos|fedora|redhat) type="yum" ;;
        debian|ubuntu|devuan) type="apt" ;;
        archlinux) type="pacman" ;;
        *)
            echo "Don't know how to manage packages on: $os" >&2
            exit 1
            ;;
    esac
fi

aptget="DEBIAN_FRONTEND=noninteractive apt-get --quiet --yes --no-install-recommends -o Dpkg::Options::=\"--force-confdef\" -o Dpkg::Options::=\"--force-confold\""

case "$type" in
    yum)
        echo "yum --quiet --assumeyes update"
        echo "yum --quiet clean all"
        ;;
    apt)
        echo $aptget dist-upgrade
        echo "apt-get --quiet autoclean"
        ;;
    pacman)
        echo "pacman --noprogressbar --noconfirm --sync --sysupgrade"
        echo "pacman --noprogressbar --noconfirm --sync --clean"
        ;;
    *)
        echo "Don't know how to manage packages on: $os" >&2
        exit 1
        ;;
esac
