#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# required
client="$(cat "$__object/parameter/client")"

# optional
export="$(cat "$__object/parameter/export" 2>/dev/null \
   || echo "/$__object_id" | tee "$__object/parameter/export")"
options="$(cat "$__object/parameter/options" 2>/dev/null || true)"
state="$(cat "$__object/parameter/state" 2>/dev/null \
   || echo "present" | tee "$__object/parameter/state")"

entry="$export"
[ -n "$options" ] && entry="$entry -${options}"
entry="$entry $client"

# NOTE: if changed, also change in explorers
prefix="#cdist:__nfs_export${export}"
suffix="#/cdist:__nfs_export${export}"
echo "$prefix" | tee "$__object/parameter/prefix" > "$__object/parameter/entry"
echo "$entry" >> "$__object/parameter/entry"
echo "$suffix" | tee "$__object/parameter/suffix" >> "$__object/parameter/entry"

exports_d="$(cat "$__object/explorer/exports.d")"
if [ "$exports_d" = "present" ]; then
   name="$(echo "$export" | sed 's;/;-;g')"
   __file "/etc/exports.d/$name" \
      --source "$__object/parameter/entry" \
      --owner root --group root --mode 644
#      --state "$state"
fi
