#!/bin/sh
#
# 2011-2014 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage packages with yum (mostly Fedora)
#

if [ -f "$__object/parameter/name" ]; then
   name="$(cat "$__object/parameter/name")"
else
   name="$__object_id"
fi

# Support installing from an URL
if [ -f "$__object/parameter/url" ]; then
   install_name="$(cat "$__object/parameter/url")"
else
   install_name="$name"
fi


state_should="$(cat "$__object/parameter/state")"

if grep -q -E "(scientific|centos|redhat|amazon)" "$__global/explorer/os"; then
    opts="-y --quiet"
else
    opts="--assumeyes --quiet"
fi

not_installed="^no package provides"

if grep -q "$not_installed" "$__object/explorer/pkg_version"; then
    state_is="absent"
else
    state_is="present"
fi

[ "$state_is" = "$state_should" ] && exit 0

case "$state_should" in
    present)
        echo yum $opts install \"$install_name\"
    ;;
    absent)
        echo yum $opts remove \"$name\"
    ;;
    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
