#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

prefix="$(cat "$__object/parameter/prefix" 2>/dev/null || echo "/target")"

[ -d "$__object/files" ] || mkdir "$__object/files"
__install_generate_fstab --uuid --destination "$__object/files/fstab"
require="__install_generate_fstab" \
   __install_file "${prefix}/etc/fstab" --source "$__object/files/fstab" \
      --mode 644 \
      --owner root \
      --group root
