#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#


case "$__arg_type" in

   directory)
      echo mkdir \"$__arg_path\"
   ;;

   file)
      echo touch \"$__arg_path\"
   ;;

   *)
      echo "Unsupported type: $__arg_type" >&2
      exit 1
   ;;

esac

if [ "$__arg_mode" ]; then
   echo chmod \"$__arg_mode\" \"$__arg_path\"
fi
