#!/bin/sh -e
#
# 2011-2013 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

uri="$(cat "$__object/parameter/uri" 2>/dev/null \
   || echo "$__object_id")"
target="$(cat "$__object/parameter/target")"

if [ "$__cdist_log_level" -le "10" ]
then
    curl="curl"
    tar="tar -xvzp"
else
    curl="curl -s"
    tar="tar -xzp"
fi

if [ -f "$__object/parameter/insecure" ] ; then
   curl="$curl -k"
fi

echo "$curl '$uri' | $tar -C '$target'"
