#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# set defaults
uri="$(cat "$__object/parameter/uri" 2>/dev/null \
   || echo "$__object_id" | tee "$__object/parameter/uri")"
target="$(cat "$__object/parameter/target" 2>/dev/null \
   || echo "/target" | tee "$__object/parameter/target")"

if [ -f "$__object/parameter/post_install" ]; then
   post_install="$(cat "$__object/parameter/post_install")"
   post_install_script="/tmp/post_install"
   __install_file $post_install_script --source $post_install
   echo "$post_install_script" > "$__object/parameter/post_install_script"
fi

