#!/bin/sh -e

uname_s="$(uname -s)"

case $uname_s in
    FreeBSD)
        sysctl -n kern.disks
    ;;
    OpenBSD)
        sysctl -n hw.disknames | grep -Eo '[lsw]d[0-9]+' | xargs
    ;;
    NetBSD)
        PATH="${PATH}:/usr/local/sbin:/usr/sbin:/sbin"
        sysctl -n hw.disknames \
        | awk 'BEGIN { RS = " " } /^[lsw]d[0-9]+/' \
        | xargs
    ;;
    Linux)
        # list of major device numbers toexclude:
        #  ram disks, floppies, cdroms
        # https://www.kernel.org/doc/Documentation/admin-guide/devices.txt
        ign_majors='1 2 11'

        if command -v lsblk >/dev/null 2>&1
        then
            lsblk -e "$(echo "$ign_majors" | tr ' ' ',')" -dno name | xargs
        elif test -d /sys/block/
        then
            # shellcheck disable=SC2012
            ls -1 /sys/block/ \
            | awk -v ign_majors="$(echo "$ign_majors" | tr ' ' '|')" '
                {
                  devfile = "/sys/block/" $0 "/dev"
                  getline devno < devfile
                  close(devfile)
                  if (devno !~ "^(" ign_majors "):") print
                }' \
            | xargs
        else
            echo "Don't know how to list disks on Linux without lsblk and sysfs." >&2
            echo 'If you can, please submit a patch.'>&2
        fi
    ;;
    *)
        printf "Don't know how to list disks for %s operating system.\n" "${uname_s}" >&2
        printf 'If you can please submit a patch\n' >&2
    ;;
esac
