#!/bin/sh
#
# 2018 Adam Dej (dejko.a at gmail.com)
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

# See os-release(5) and http://0pointer.de/blog/projects/os-release

if test -f /etc/os-release
then
	# Linux and FreeBSD (usually a symlink)
	cat /etc/os-release
elif test -f /usr/lib/os-release
then
	# systemd
	cat /usr/lib/os-release
elif test -f /var/run/os-release
then
	# FreeBSD (created by os-release service)
	cat /var/run/os-release
fi

