#!/bin/sh
#
# 2018 Stu Zhao (z12y12l12 at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.

if [ -f "$__object/parameter/type" ]; then
    cat "$__object/parameter/type"
else
    # By default determine package manager based on operating system
    os="$("$__explorer/os")"
    case "$os" in
        amazon|scientific|centos|fedora|redhat) echo "yum" ;;
        debian|ubuntu|devuan) echo "apt" ;;
        archlinux) echo "pacman" ;;
        *)
            echo "Don't know how to manage packages on: $os" >&2
            exit 1
            ;;
    esac
fi
