#!/bin/sh
#
# 2012 Benedikt Koeppel (code@benediktkoeppel.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

# to the database without requiring a passwort input
rootpassword="$(cat "$__object/parameter/password")"

# set root password
echo "mysqladmin -u root password $rootpassword"

# store the root password in /root/.my.cnf so that processes can connect
cat <<-EOFF
cat <<-EOF > /root/.my.cnf
	[client]
	password=$rootpassword
EOF
EOFF

# remove anonymous users
cat <<-EOFF
mysql -u root <<-EOF
	DELETE FROM mysql.user WHERE User='';
EOF
EOFF

# remove remote-access for root
cat <<-EOFF
mysql -u root <<-EOF
	DELETE FROM mysql.user WHERE User='root' AND Host!='localhost';
EOF
EOFF

# remove test database
cat <<-EOFF
mysql -u root <<-EOF
	DROP DATABASE IF EXISTS test;
EOF
EOFF
cat <<-EOFF
mysql -u root <<-EOF
	DELETE FROM mysql.db WHERE Db='test' OR Db='test\_%'
EOF
EOFF

# flush privileges
cat <<-EOFF
mysql -u root <<-EOF
	FLUSH PRIVILEGES;
EOF
EOFF

