#!/bin/sh
#
# 2012-2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

owner="$(cat "$__object/parameter/owner" 2>/dev/null || echo "$__object_id")"
state="$(cat "$__object/parameter/state" 2>/dev/null)"
file="$(cat "$__object/explorer/file")"

if [ ! -f "$__object/parameter/noparent" -o ! -f "$__object/parameter/nofile" ]; then
   group="$(cut -d':' -f 1 "$__object/explorer/group")"
   if [ -z "$group" ]; then
      echo "Failed to get owners group from explorer." >&2
      exit 1
   fi

   if [ ! -f "$__object/parameter/noparent" ]; then
      __ssh_dot_ssh "$owner"
      export require="__ssh_dot_ssh/$owner"
   fi
   if [ ! -f "$__object/parameter/nofile" ]; then
      # Ensure that authorized_keys file exists and has the right permissions.
      __file "$file" \
         --owner "$owner" \
         --group "$group" \
         --mode 0600 \
         --state exists
      export require="__file/$file"
   fi
fi

# Remove legacy blocks created by old versions of this type
# FIXME: remove me in 3.2+
__block "$__object_name" \
   --file "$file" \
   --prefix "#cdist:$__object_name" \
   --suffix "#/cdist:$__object_name" \
   --state 'absent' \
   --text - << DONE
remove legacy block
DONE
export require="__block/$__object_name"

_cksum() {
   echo "$1" | cksum | cut -d' ' -f 1
}

while read key; do
   type_and_key="$(echo "$key" | tr ' ' '\n' | awk '/^(ssh|ecdsa)-[^ ]+/ { printf $1" "; getline; printf $1 }')"
   object_id="$(_cksum "$file")-$(_cksum "$type_and_key")"
   set -- "$object_id"
   set -- "$@" --file "$file"
   set -- "$@" --key "$key"
   set -- "$@" --state "$state"
   if [ -f "$__object/parameter/option" ]; then
      set -- "$@" --option "$(cat "$__object/parameter/option")"
   fi
   if [ -f "$__object/parameter/comment" ]; then
      set -- "$@" --comment "$(cat "$__object/parameter/comment")"
   fi
   # Ensure __ssh_authorized_key does not read stdin
   __ssh_authorized_key "$@" < /dev/null
done < "$__object/parameter/key"
