#!/bin/sh
#
# 2012 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

owner="$(cat "$__object/parameter/owner" 2>/dev/null || echo "$__object_id")"
state="$(cat "$__object/parameter/state" 2>/dev/null)"
if [ -f "$__object/parameter/file" ]; then
   file="$(cat "$__object/parameter/file")"
else
   home="$(cut -d':' -f 6 "$__object/explorer/passwd")"
   if [ -z "$home" ]; then
      echo "Failed to get home directory from explorer." >&2
      exit 1
   fi
   file="$home/.ssh/authorized_keys"
fi

if [ ! -f "$__object/parameter/noparent" -o ! -f "$__object/parameter/nofile" ]; then
   group="$(cut -d':' -f 4 "$__object/explorer/passwd")"
   if [ -z "$group" ]; then
      echo "Failed to get owners group from explorer." >&2
      exit 1
   fi

   if [ ! -f "$__object/parameter/noparent" ]; then
      # Ensure that the directory in which the authorized_keys shall be exists and
      # has the right permissions.
      ssh_directory="${file%/*}"
      __directory "$ssh_directory" --state present --parents \
         --owner "$owner" --group "$group" --mode 0700
      export require="__directory/$ssh_directory"
   fi
   if [ ! -f "$__object/parameter/nofile" ]; then
      # Ensure that authorized_keys file exists and has the right permissions.
      __file "$file" \
         --owner "$owner" \
         --group "$group" \
         --mode 0600 \
         --state exists
   fi
fi

# Generate entry for inclusion in authorized_keys file
(
if [ -f "$__object/parameter/comment" ]; then
   echo "# $(cat "$__object/parameter/comment")"
fi
cat "$__object/parameter/key"
) | \
__block "$__object_name" \
   --file "$file" \
   --prefix "#cdist:$__object_name" \
   --suffix "#/cdist:$__object_name" \
   --state "$state" \
   --text -
