#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

cat << DONE
output_if_debug() {
   if [ "$__debug" = "yes" ]; then
      cat
   else
      cat >> /dev/null
   fi
}
DONE

# required
target="$(cat "$__object/parameter/target")"
suite="$(cat "$__object/parameter/suite")"

# optional
arch="$(cat "$__object/parameter/arch" 2>/dev/null || true)"
mirror="$(cat "$__object/parameter/mirror" 2>/dev/null || true)"
script="$(cat "$__object/parameter/script" 2>/dev/null || true)"

state="$(cat "$__object/explorer/state")"
if [ "$state" = "absent" ]; then
   printf "debootstrap"
   case "$arch" in
      x86_64) printf " --arch=amd64" ;;
      '') : ;;
      *) printf " --arch=$arch"
   esac
   printf " $suite $target"
   [ -n "$mirror" ] && printf " $mirror"
   [ -n "$script" ] && printf " $script"
   printf " | output_if_debug\n"
fi
