#!/bin/sh
#
# 2021 Matthias Stecher (matthiasstecher at gmx.de)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


nameparam="$__object/parameter/name"
if [ -f "$nameparam" ]; then
    name=$(cat "$nameparam")
else
    name="$__object_id"
fi

pipparam="$__object/parameter/pip"
if [ -f "$pipparam" ]; then
    pip=$(cat "$pipparam")
else
    pip="$( "$__type_explorer/pip" )"
fi


if command -v "$pip" >/dev/null 2>&1; then
    # assemble the path where pip stores all pip package info
    "$pip" show "$name" \
        | awk -F': ' '
            $1 == "Name" {name=$2; gsub(/-/,"_",name); next}
            $1 == "Version" {version=$2; next}
            $1 == "Location" {location=$2; next}
            END {if (version != "") printf "%s/%s-%s.dist-info", location, name, version}'
fi
