#!/bin/sh -e

certbot_path=$("${__type_explorer}/certbot-path")
if [ -n "${certbot_path}" ]
then
	if certbot certificates --cert-name "${__object_id:?}" | \
		grep -q 'INVALID: TEST_CERT'; then
		echo yes
	else
		echo no
	fi
else
	echo no
fi
