#!/bin/sh -e

certbot_path=$("${__type_explorer}/certbot-path")
if [ -n "${certbot_path}" ]
then
	certbot certificates --cert-name "${__object_id:?}" | grep '    Domains: ' | \
		cut -d ' ' -f 6- | tr ' ' '\n'
fi
