#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

name="$__object_id"
state_is="$(cat "$__object/explorer/state")"
state_should="$(cat "$__object/parameter/state")"

if [ "$state_is" != "$state_should" ]; then
   case "$state_should" in
      present)
         optional="password
         login
         createdb
         createrole
         superuser"
         for parameter in $optional; do
            if [ -f "$__object/parameter/$parameter" ]; then
               value="$(cat "$__object/parameter/$parameter")"
               eval $parameter=$value
            fi
         done

         [ -n "$password" ] && password="PASSWORD '$password'"
         [ "$login" = "true" ] && login="LOGIN" || login="NOLOGIN"
         [ "$createdb" = "true" ] && createdb="CREATEDB" || createdb="NOCREATEDB"
         [ "$createrole" = "true" ] && createrole="CREATEROLE" || createrole="NOCREATEROLE"
         [ "$superuser" = "true" ] && superuser="SUPERUSER" || superuser="NOSUPERUSER"
         [ "$inherit" = "true" ] && inherit="INHERIT" || inherit="NOINHERIT"

         cmd="CREATE ROLE $name WITH $password $login $createdb $createrole $superuser $inherit"
         echo "su - postgres -c \"psql -c \\\"$cmd\\\"\""
      ;;
      absent)
         echo "su - postgres -c \"dropuser \\\"$name\\\"\""
      ;;
   esac
fi
