#!/bin/sh
#
# 2011-2012 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage packages with Pacman (mostly archlinux)
#

# Debug
# exec >&2
# set -x

if [ -f "$__object/parameter/name" ]; then
   name="$__object/parameter/name"
else
   name="$__object_id"
fi

state_should="$(cat "$__object/parameter/state")"

pkg_version="$(cat "$__object/explorer/pkg_version")"
if [ -z "$pkg_version" ]; then
    state_is="absent"
else
    state_is="present"
fi

# Exit if nothing is needed to be done
[ "$state_is" = "$state_should" ] && exit 0

case "$state_should" in
   present)
         echo pacman --needed --noconfirm --noprogressbar -S \"$name\"
   ;;
   absent)
         echo pacman --noconfirm --noprogressbar -R \"$name\"
   ;;
   *)
      echo "Unknown state: $state_should" >&2
      exit 1
   ;;
esac
