#!/bin/sh
#
# 2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -s "$__object/parameter/owner" ]
then
	owner=$(cat "$__object/parameter/owner")
else
	owner="$__object_id"
fi

if command -v getent >/dev/null
then
	gid=$(getent passwd "$owner" | cut -d':' -f4)
	getent group "$gid" || true
else
	# Fallback to local file scanning
	case $owner
	in
		[0-9][0-9]*)
			gid=$(awk -F: "\$3 == \"${owner}\" { print \$4 }" /etc/passwd)
			;;
		*)
			gid=$(awk -F: "\$1 == \"${owner}\" { print \$4 }" /etc/passwd)
			;;
	esac

	awk -F: "\$3 == \"$gid\" { print }" /etc/group
fi
