#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Get an existing groups gshadow entry.
#

name=$__object_id
os_version="$($__explorer/os_version)"
os="$($__explorer/os)"

if [ "$os" = "freebsd" ]; then
   echo "FreeBSD does not have getent gshadow"
   exit 0
fi

case "$os_version" in
   "Red Hat Enterprise Linux Server release "[45]*|"CentOS release "[45]*)
      # TODO: find a way to get this information
      echo "$os_version does not have getent gshadow"
   ;;
   *)
      getent gshadow "$name" || true
   ;;
esac

