#!/bin/sh
#
# Copyright (C) 2011 Daniel Maher (phrawzty+cdist at gmail.com)
#
# This file is part of cdist (https://github.com/telmich/cdist/).
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ "$__object/parameter/source" ]; then
    source="$(cat "$__object/parameter/source")"
else
    source="/$__object_id"
fi

# Remove the cruft from the state file; we want to compare apples to apples.
md5_src="$(export LC_ALL=C && cat $source | grep -v "^#" | cut -d '[' -f 1 | sort | md5sum | cut -d ' ' -f 1)"
md5_dst="$(cat "$__object/explorer/md5sum")"

echo "iptables_restore src : $md5_src" >&2
echo "iptables_restore dst : $md5_dst" >&2

if [ "$md5_src" != "$md5_dst" ]; then
    mkdir "$__object/files"
    touch "$__object/files/restore"
    __file "/tmp/source.iptables" --source $source
fi
