#!/bin/sh
#
# 2012 Nico Schottelius (nico-cdist at schottelius.org)
# 2016 Darko Poljak (darko.poljak at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Development supported by Local AG (www.local.ch)
#

state_is=$(cat "$__object/explorer/state")
state_should="$(cat "$__object/parameter/state")"

[ "$state_is" = "$state_should" ] && exit 0

nameparam="$__object/parameter/name"
if [ -f "$nameparam" ]; then
    name=$(cat "$nameparam")
else
    name="$__object_id"
fi

pipparam="$__object/parameter/pip"
if [ -f "$pipparam" ]; then
    pip=$(cat "$pipparam")
else
    pip="pip"
fi

runasparam="$__object/parameter/runas"
if [ -f "$runasparam" ]
then
    runas=$(cat "$runasparam")
else
    runas=""
fi

case "$state_should" in
    present)
        if [ "$runas" ]
        then
            echo "su -c \"$pip install -q $name\" $runas"
        else
            echo $pip install -q "$name"
        fi
    ;;
    absent)
        if [ "$runas" ]
        then
            echo "su -c \"$pip uninstall -q -y $name\" $runas"
        else
            echo $pip uninstall -q -y "$name"
        fi
    ;;
    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
