#!/bin/sh
#
# 2015 Dominique Roux (dominique.roux4 at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

if [ -f "$__object/parameter/destination" ]; then
    destination=$(cat "$__object/parameter/destination")
else
    destination="/$__object_id"
fi

ownergroup=""
if [ -f "$__object/parameter/owner" ]; then
    ownergroup=$(cat "$__object/parameter/owner")
fi
if [ -f "$__object/parameter/group" ]; then
    ownergroup="${ownergroup}:$(cat "$__object/parameter/group")"
fi

if [ "$ownergroup" ]; then
    echo chown -R "$ownergroup" "$destination"
fi
