#!/bin/sh
#
# 2015 Dominique Roux (dominique.roux4 at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

source=$(cat "$__object/parameter/source")
remote_user=$(cat "$__object/parameter/remote-user")

if [ -f "$__object/parameter/destination" ]; then
    destination=$(cat "$__object/parameter/destination")
else
    destination="/$__object_id"
fi

set --
if [ -f "$__object/parameter/rsync-opts" ]; then
    while read opts; do
        set -- "$@" "--$opts"
    done < $__object/parameter/rsync-opts
fi

echo rsync -a \
    --no-owner --no-group \
    -q "$@" "${source}/" "${remote_user}@${__target_host}:${destination}"
