#!/bin/sh -e
#
# 2011-2017 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

chroot="$(cat "$__object/parameter/chroot")"
remote_exec="$__type/files/remote/exec"
remote_copy="$__type/files/remote/copy"

cdist_args=""
case "$__cdist_loglevel" in
   20)
      cdist_args="-v"
   ;;
   15)
      cdist_args="-vv"
   ;;
   10)
      cdist_args="-vvv"
   ;;
   5)
      cdist_args="-vvvv"
   ;;
esac

cat << DONE
export __default_remote_exec="$__remote_exec"
export __default_remote_copy="$__remote_copy"
cdist config \
   $cdist_args \
   --remote-exec="$remote_exec $chroot" \
   --remote-copy="$remote_copy $chroot" \
   $__target_host
DONE

