#!/bin/sh
#
# 2012-2014 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Hacked in Kalamata, Greece
#

owner="$__object_id"
state="$(cat "$__object/parameter/state")"

group="$(cut -d':' -f 1 "$__object/explorer/group")"
if [ -z "$group" ]; then
    echo "Failed to get owners group from explorer." >&2
    exit 1
fi

home="$(cut -d':' -f 6 "$__object/explorer/passwd")"
if [ -z "$home" ]; then
   echo "Failed to get home directory from explorer." >&2
   exit 1
fi
ssh_directory="${home}/.ssh"

# Ensure that the directory in which the authorized_keys shall be exists and
# has the right permissions.
__directory "$ssh_directory" \
    --state "$state" \
    --owner "$owner" --group "$group" --mode 0700
