#!/bin/sh -e

if [ -f "$__object/parameter/file" ]
then
    file="$( cat "$__object/parameter/file" )"
else
    file="/$__object_id"
fi

if [ ! -e "$file" ]
then
    echo "$file do not exist" >&2
    exit 1
fi

cat "$file"
