#!/bin/sh -e

if [ -f "$__object/parameter/cmd-get" ]
then
    cat "$__object/parameter/cmd-get"
elif
    command -v curl > /dev/null
then
    echo "curl -sSL -o - '%s'"
elif
    command -v fetch > /dev/null
then
    echo "fetch -o - '%s'"
else
    echo "wget -O - '%s'"
fi
