#!/bin/sh
#
# 2012 Jake Guffey (jake.guffey at eprotex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# See if the jailbase.tgz or $jaildir/base dir exists
#

# Debug
#exec >&2
#set -x

if [ -f "$__object/parameter/jaildir" ]; then
   jaildir="$(cat "$__object/parameter/jaildir")"
else
   jaildir="/usr/jail"
fi

name="base:jailbase.tgz"
out=""

save_IFS="$IFS"
IFS=":"
for cur in $name; do
    if [ -e "${jaildir}/$cur" ]; then
        out="${out}:${cur}"
    fi
done
IFS="$save_IFS"

if [ -z "$out" ]; then
    echo "NONE"
else
    echo "${out}"
fi

# Debug
#set +x

