#!/bin/sh -e
#
# 2018-2019 Thomas Eckert (tom at it-eckert.de)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.

## "move" user-modified dirs to /etc/xymon to be managed by __xymon_config:
cat <<-EOT
	if [ ! -L /usr/lib/xymon/server/ext ]; then
		mv /usr/lib/xymon/server/ext /etc/xymon
		ln -s /etc/xymon/ext /usr/lib/xymon/server/
	fi	
EOT
