#!/bin/sh -e
#
# 2018-2019 Thomas Eckert (tom at it-eckert.de)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.

state=$(cat "$__object/parameter/state")
if [ -f "$__object/parameter/install_helpers" ]; then
	install_helpers=1
else
	install_helpers=0
fi

os=$(cat "$__global/explorer/os")
case "$os" in
	debian|ubuntu)
		:
	;;
	*)
		echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
		echo "Please contribute an implementation for it if you can." >&2
		exit 1
	;;
esac

__package xymon --state "$state"

## install helper-packages/tools used by the xymon server if requested:
if [ "$install_helpers" = "1" ]; then
	__package fping --state "$state"
	__package heirloom-mailx --state "$state"
	__package traceroute --state "$state"
	__package ntpdate --state "$state"
fi

## CLI-usage often requires a shell:
require="__package/xymon" __user xymon --shell "/bin/bash" --state "$state"
