#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __file is a very basic type and should be able to be used as an
# example for typewrites later
#

. cdist-config

pwd -P >&2
ls >&2

type="$(cat type)"
path="$(cat destination)"

case "$type" in
   directory)
      echo mkdir \"$path\"
   ;;

   file)
      echo touch \"$path\"
   ;;

   *)
      echo "Unsupported type: \"$type\"" >&2
      exit 1
   ;;

esac

if [ -f mode ]; then
   mode="$(cat mode)"
   echo chmod \"$mode\" \"$path\"
fi
