#!/bin/sh
#
# 2016 Darko Poljak (darko.poljak at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# It assumes pyvenv is already installed. Concrete packages
# or installation procedures depend on concrete OS and/or OS
# version/distribution.

state_should="$(cat "$__object/parameter/state")"
owner="$(cat "$__object/parameter/owner")"
group="$(cat "$__object/parameter/group")"
mode="$(cat "$__object/parameter/mode")"

case "$state_should" in
    present)
        :
    ;;

    absent)
        __directory "$__object_id" --state absent \
            --owner "$owner" \
            --group "$group" \
            --mode "$mode"
    ;;

    *)
        echo "Unknown state: $state_should" >&2
        exit 1
    ;;
esac
