#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

export key="$(cat "$__object/parameter/key" 2>/dev/null \
   || echo "$__object_id")"
export state="$(cat "$__object/parameter/state" 2>/dev/null \
   || echo "present")"
file="$(cat "$__object/parameter/file")"
export delimiter="$(cat "$__object/parameter/delimiter")"
export value="$(cat "$__object/parameter/value" 2>/dev/null \
   || echo "__CDIST_NOTSET__")"

awk -f - "$file" <<"AWK_EOF"
BEGIN {
    state=ENVIRON["state"]
    key=ENVIRON["key"]
    delimiter=ENVIRON["delimiter"]
    value=ENVIRON["value"]
    keydel=key delimiter
    line=keydel value
    found=0
}
# enter the main loop
{
    i = index($0,keydel)
    if(i == 1) {
        found=1
        if(state == "absent") {
            # on state absent, only the ocurance is relevant, so exit here
            print "present"
            exit
        }
        # Key with separator found
        if($0 == line) {
            # exact match found, so state is present
            print "present"
        }
        else {
            # not value is wrong ...
            print "wrongvalue"
        }
        exit
    }
}
END {
    if(found == 0)
        print "absent"
}
AWK_EOF
