#!/bin/sh -e
#
# 2019 Nico Schottelius (nico-cdist at schottelius.org)
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
# Manage users.
#

case $(cat "${__global}/explorer/os")
in
	(alpine)
		__package shadow
		;;
	(openwrt)
		case $(cat "${__object}/parameter/state")
		in
			(present)
				if test -s "${__object}/explorer/passwd"
				then
					# NOTE: The package might not be required if no changes
					# are required, but determining if changes are required is
					# out of scope here, and 40k should be okay, I hope.
					__package shadow-usermod
				else
					__package shadow-useradd
				fi
				;;
			(absent)
				if test -s "${__object}/explorer/passwd"
				then
					__package shadow-userdel
				fi
				;;
		esac
		;;
	(*)
		:
		;;
esac
