#!/bin/sh
#
# Copyright (C) 2011 Daniel Maher (phrawzty+cdist at gmail.com)
#
# This file is part of cdist (https://github.com/telmich/cdist/).
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# The marker file is established in the docs, but it isn't obligatory.
if [ -f "$__object/parameter/destination" ]; then
    destination="$(cat "$__object/parameter/destination")"
else
    destination='/etc/cdist-configured'
fi

# The basic output of date is usually good enough, but variety is the
#   spice of life...
if [ -f "$__object/parameter/format" ]; then
    format="$(cat "$__object/parameter/format")"
else
    format='-u'
fi

# Dump the timestamp in UTC to the marker
echo "date $format > $destination"
