#!/bin/sh
#
# 2011 - 2012 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

candidates="/etc/auto.master /etc/autofs/auto.master"
find_auto_master() {
   # get the path of the auto.master file
   for candidate in $candidates; do
      if [ -f "$candidate" ]; then
         echo "$candidate"
         return
      fi
   done
}

auto_master="$(find_auto_master)"

# no auto.master, nothing we could do
[ -f "$auto_master" ] || exit 0

# NOTE: keep variables in sync in manifest/explorer/gencode-*
prefix="#cdist:$__object_name"
suffix="#/cdist:$__object_name"
awk -v prefix="$prefix" -v suffix="$suffix" '{
   if (index($0,prefix)) {
      triggered=1
   }
   if (triggered) {
      if (index($0,suffix)) {
            triggered=0
      }
      print
   }
}' "$auto_master"
