#!/bin/sh
#
# 2011-2013 Steven Armstrong (steven-cdist at armstrong.cc)
# 2017      Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

device="$(cat "$__object/parameter/device")"
type="$(cat "$__object/parameter/type")"

case "$type" in
    swap)
        echo "mkswap $device"
        exit 0
        ;;
    xfs)
        command="mkfs.xfs -f -q"
        ;;

    vfat)
        command="mkfs.vfat"
        ;;

    *)
        command="mkfs -t $type -q"
        ;;
esac

if [ -f "$__object/parameter/options" ]; then
    options="$(cat "$__object/parameter/options")"
    command="$command $options"
fi

command="$command $device"
if [ -f "$__object/parameter/blocks" ]; then
    blocks="$(cat "$__object/parameter/blocks")"
    command="$command $blocks"
fi
echo "$command"
