#!/bin/sh
#
# 2012 Jake Guffey (jake.guffey at eprotex.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Build ports on FreeBSD
#

assert ()                 #  If condition false,
{                         #+ exit from script with error message.
	E_PARAM_ERR=98
	E_ASSERT_FAILED=99

	if [ -z "$2" ]          # Not enough parameters passed.
	then
		return $E_PARAM_ERR   # No damage done.
	fi

	lineno=$2

	if [ ! $1 ] 
	then
		echo "Assertion failed:  \"$1\""
		echo "File \"$0\", line $lineno, called by $(caller 0)"
		exit $E_ASSERT_FAILED
	fi  
}

# Debug
#exec >&2
#set -x

if [ -f "$__object/parameter/name" ]; then
	name="$__object/parameter/name"
else
	name="$__object_id"
fi

# Get list of installed ports
installed="$(cat "$__object/explorer/installed")"

# Is port already built/installed? Check /var/db/ports
for PORT in $installed; do
   if [ "$(eval "$PORT" : "$name")" != 0 ]; then	# already installed
      exit 0;
   fi
done

# If not, build
echo "cd /usr/ports && "

# Debug
#set +x

