#!/bin/sh
#
# 2013-2014 Nico Schottelius (nico-cdist at schottelius.org)
# 2014 Ricardo Catalinas Jiménez (jimenezrick at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Install required packages and set up config
#

locale="$(cat "$__object/parameter/locale")"
charset="$(cat "$__object/parameter/charset")"
os="$(cat "$__global/explorer/os")"

case "$os" in
    debian|ubuntu)
        # Debian needs a seperate package
        __package locales --state present
    ;;
    archlinux|suse)
        :
    ;;
    *)
        echo "Sorry, do not know how to handle os: $os" >&2
        echo "Please edit the type ${__type##*/} to fix this." >&2
        exit 1
    ;;
esac

__line /etc/locale.gen --line "$locale $charset" --state present
