#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Retrieve the md5sum of a file to be created, if it is already existing.
#

if [ -f "$__object/parameter/destination" ]; then
   destination="$(cat "$__object/parameter/destination")"
else
   destination="/$__object_id"
fi

os="$(cat $__global/explorer/os)"

case "$os" in
   macosx)
      md5sum="md5"
   ;;

   *)
      md5sum="md5sum"
   ;;
esac

# No output if file does not exist - does definitely not match the md5sum :-)
if [ -e "$destination" ]; then
   $md5sum < "$destination"
else
   echo "NO FILE FOUND, NO CHECKSUM CALCULATED."
fi
