#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Retrieve some stat related data from a file if it is already existing.
#

destination="/$__object_id"

if [ -e "$destination" ]; then
   if [ -f  "$destination" ]; then
      mode=$(ls -l -- "$destination" | sed 's/.\(.........\).*/\1/
h;y/rwsxtST-/IIIIIOOO/;x;s/..\(.\)..\(.\)..\(.\)/|\1\2\3/
y/sStTx-/IIIIOO/;G
s/\n\(.*\)/\1;OOO0OOI1OIO2OII3IOO4IOI5IIO6III7/;:k
s/|\(...\)\(.*;.*\1\(.\)\)/\3|\2/;tk
s/^0*\(..*\)|.*/\1/;q')
      owner=$(ls -l "$destination" | awk '{print $3}')
      uid=$(ls -n "$destination" | awk '{print $3}')
      group=$(ls -l "$destination" | awk '{print $4}')
      gid=$(ls -n "$destination" | awk '{print $4}')
      echo "mode $mode
owner $owner
uid $uid
group $group
gid $gid"
   else
      echo "NOT A REGULAR FILE"
   fi
else
   echo "NO FILE FOUND, NO STAT DATA COLLECTED"
fi
