#!/bin/sh
#
# 2013 Steven Armstrong (steven-cdist armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Mostly a wrapper for ln
#

destination="/$__object_id"

if [ ! -e "$destination" ]; then
   echo none
elif [ -h "$destination" ]; then
   echo symlink
elif [ -f "$destination" ]; then
   type="$(cat "$__object/parameter/type")"
   case "$type" in
      hard)
         link_count=$(ls -l "$destination" | awk '{ print $2 }')
         if [ $link_count -gt 1 ]; then
            echo hardlink
            exit 0
         fi
      ;;
   esac
   echo file
elif [ -d "$destination" ]; then
   echo directory
else
   echo unknown
fi
