#!/bin/sh
set -x
os="$(cat "$__global/explorer/os")"
machine="$(cat "$__global/explorer/machine")"
hostname="$(cat "$__global/explorer/hostname")"
case "$os" in
	macosx)
		__file /var/root/fusioninventory-agent_macosx.zip --source "$__type/files/fusioninventory-agent_macosx.zip"
	require="__file/var/root/fusioninventory-agent_macosx.zip" __unzip /var/root/fusioninventory-agent_macosx.zip --dir /var/root
	require="__unzip/var/root/fusioninventory-agent_macosx.zip" __file agent.cfg --source "$__type/files/agent.cfg"
	require="__unzip/var/root/fusioninventory-agent_macosx.zip" __file cacert.pem --source "$__type/files/cacert.pem"
	;;

	archlinux)
		echo "Utiliser cpan"
	;;

	centos|redhat|fedora)
		__file /root/fusioninventory-agent_rh_$machine.zip --source "$__type/files/fusioninventory-agent_rh_$machine.zip"
	require="__file/root/fusioninventory-agent_rh_$machine.zip" __unzip /root/fusioninventory-agent_rh_$machine.zip --dir /root
	require="__unzip/root/fusioninventory-agent_rh_$machine.zip" __file /root/fusioninventory-agent/agent.cfg --source "$__type/files/agent.cfg"
	require="__unzip/root/fusioninventory-agent_rh_$machine.zip" __file cacert.pem --source "$__type/files/cacert.pem"
	;;

	ubuntu)
		__file /root/fusioninventory-agent_ubuntu_$machine.zip --source "$__type/files/fusioninventory-agent_ubuntu_$machine.zip"
	require="__file/root/fusioninventory-agent_ubuntu_$machine.zip" __unzip /root/fusioninventory-agent_ubuntu_$machine.zip --dir /root
	require="__unzip/root/fusioninventory-agent_ubuntu_$machine.zip" __file /root/fusioninventory-agent/agent.cfg --source "$__type/files/agent.cfg"
	require="__unzip/root/fusioninventory-agent_ubuntu_$machine.zip" __file cacert.pem --source "$__type/files/cacert.pem"
	;;

	*)
		echo "Pas encore supporte"
	;;
esac
