#!/bin/sh -e
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2013 Tomas Pospisek (tpo_deb at sourcepole.ch)
# 2021 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This type was created by Tomas Pospisek based on the
# __postgres_role type by Steven Armstrong.
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

postgres_user=$(cat "${__object:?}/explorer/postgres_user")

quote() { printf '%s\n' "$*" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/'/"; }
psql_cmd() {
	printf 'su - %s -c %s\n' \
		"$(quote "${postgres_user}")" \
		"$(quote psql "$(quote "$1")" -c "$(quote "$2")")"
}


IFS=: read -r dbname extname <<EOF
${__object_id:?}
EOF

state_is=$(cat "${__object:?}/explorer/state")
state_should=$(cat "${__object:?}/parameter/state")

if test "${state_is}" = "${state_should}"
then
	exit 0
fi

case ${state_should}
in
	(present)
		psql_cmd "${dbname}" "CREATE EXTENSION ${extname}"
		;;
	(absent)
		psql_cmd "${dbname}" "DROP EXTENSION ${extname}"
		;;
	(*)
		printf 'Invalid --state: %s\n' "${state_should}" >&2
		exit 1
		;;
esac
