#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __remote_copy script to run cdist against a chroot on a remote host via ssh.
#
# Usage:
#  __remote_copy="/path/to/this/script /path/to/your/chroot" cdist config target-id
#

log() {
   echo "$@" | logger -t "__install_config copy"
   :
}

chroot="$1"; shift
target_host="$__target_host"

scp="scp -o User=root -q"

# postfix target_host with chroot location
code="$(echo "$@" | sed "s|$target_host:|$target_host:$chroot|g")"

log "target_host: $target_host"
log "chroot: $chroot"
log "@: $@"
log "code: $code"

# copy files into chroot
$scp $code

log "-----"
