#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# __remote_exec script to run cdist against a chroot on a remote host via ssh.
#
# Usage:
#  __remote_exec="/path/to/this/script /path/to/your/chroot" cdist config target-id
#

log() {
   echo "$@" | logger -t "__install_config exec"
   :
}

chroot="$1"; shift
target_host="$__target_host"
# In exec mode the first argument is the __target_host which we already got from env. Get rid of it.
shift

ssh="ssh -o User=root -q $target_host"
scp="scp -o User=root -q"

local_script=$(mktemp "/tmp/chroot-${0##*/}.XXXXXXXXXX")
remote_script=$($ssh mktemp "${chroot}/tmp/chroot-${0##*/}.XXXXXXXXXX")
relative_script="${remote_script#$chroot}"
trap cleanup INT TERM EXIT
cleanup() {
   [ $__cdist_debug ] || {
      rm "$local_script"
      $ssh "rm $remote_script";
   }
}

log "chroot: $chroot"
log "target_host: $target_host"
log "local_script: $local_script"
log "remote_script: $remote_script"
log "relative_script: $relative_script"
log "@: $@"
cat > "$local_script" << DONE
#!/bin/sh -l
# FIXME: fix the dependency bug, then test if the below is required or not
#if [ -f /etc/environment ]; then
#   . /etc/environment
#fi
$@
DONE

# Upload script to target
$scp $local_script $target_host:$remote_script
$ssh "chmod +x $remote_script"

# run in chroot
$ssh "chroot $chroot $relative_script"

log "-----"
