#!/bin/sh -e
#
# 2016 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

chroot="/$__object_id"

if [ -f "$__object/parameter/manage-resolv-conf" ]; then
   suffix="$(cat "$__object/parameter/manage-resolv-conf")"
   resolv_conf="${chroot}/etc/resolv.conf"
   original_resolv_conf="${resolv_conf}.${suffix}"
   cat << DONE
$__remote_exec $__target_host << EOSSH
if [ -f "${resolv_conf}" ]; then
   mv "${resolv_conf}" "${original_resolv_conf}"
fi
# copy hosts resolv.conf into chroot
cp /etc/resolv.conf "${resolv_conf}"
EOSSH
DONE
fi
