#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage users.
#

name="$__object_id"

cd "$__object/parameter"
if grep -q "^${name}:" "$__object/explorer/passwd"; then
   for property in $(ls .); do
      new_value="$(cat "$property")"

      file="$__object/explorer/passwd"

      case "$property" in
         password)
            field=3 
            file="$__object/explorer/shadow"
         ;;
         gid)
            if $(echo "$new_value" | grep -q '^[0-9][0-9]*$'); then
               field=4
            else
               # group name
               file="$__object/explorer/group"
               field=1
            fi
         ;;
         uid)     field=3 ;;
         comment) field=5 ;;
         home)    field=6 ;;
         shell)   field=7 ;;
      esac

      export field
      current_value="$(awk -F: '{ print $ENVIRON["field"] }' < "$file")"

      if [ "$new_value" != "$current_value" ]; then
         set -- "$@" "--$property" \"$new_value\"
      fi
   done

   [ $# -gt 0 ] && echo usermod "$@" "$name"
else
   for property in $(ls .); do
      new_value="$(cat "$property")"
      set -- "$@" "--$property" \"$new_value\"
   done

   echo useradd "$@" "$name"
fi
