#!/bin/sh
#
# 2015 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

set -- "/${__object_id}"
for param in $(ls "$__object/parameter/"); do
   case "$param" in
      source)
         source="$(cat "$__object/parameter/source")"
         if [ "$source" = "-" ]; then
            source="$__object/stdin"
         fi
         set -- "$@" --source "$source"
      ;;
      owner|group|mode|state)
         set -- "$@" "--${param}" "$(cat "$__object/parameter/$param")"
      ;;
      *)
         # ignore unknown parameters
         :
      ;;
   esac
done

__file "$@"
