#!/bin/sh
#
# 2012 Steven Armstrong (steven-cdist at armstrong.cc)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

user="$(cat "$__object/parameter/user" 2>/dev/null || echo "$__object_id")"
state_should="$(cat "$__object/parameter/state")"
oldusermod="$(cat "$__object/explorer/oldusermod")"
os=$(cat "$__global/explorer/os")

if [ "$os" = "freebsd" ]; then
	cmd="pw groupmod \"\$group\" \$action \"\$user\""
	addparam="-m"
	delparam="-d"
elif [ "$os" = "netbsd" ]; then
	# NetBSD does not have a command to remove a user from a group
	cmd="usermod \$action \"\$group\" \"\$user\""
	addparam="-G"
	delparam=";;#"
elif [ "$oldusermod" = "true" ]; then
	cmd="usermod \$action \"\$group\" \"\$user\""
	addparam="-A"
	delparam="-R"
else
	cmd="gpasswd \$action \"\$user\" \"\$group\""
	addparam="-a"
	delparam="-d"
fi

mkdir "$__object/files"
# file has to be sorted for comparison with `comm`
sort "$__object/parameter/group" > "$__object/files/group.sorted"

case "$state_should" in
   present)
      changed_groups="$(comm -13 "$__object/explorer/group" "$__object/files/group.sorted")"
      action="$addparam"
   ;;
   absent)
      changed_groups="$(comm -12 "$__object/explorer/group" "$__object/files/group.sorted")"
      action="$delparam"
   ;;
esac

if [ -z "$changed_groups" ]; then
   # Nothing to do, move along
   exit 0
fi

for group in $changed_groups; do
   eval "echo $cmd"
done
