#!/bin/sh -e
#
# 2020 Dennis Camera (dennis.camera@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

transaction_name=${__object_id:?}
batchfile="${__global:?}/tmp/__uci/${transaction_name}.txt"

test -s "${batchfile}" || exit 0

if test -s "${__object:?}/explorer/changes"
then
	echo 'Uncommited UCI changes were found on the target:'
	cat "${__object:?}/explorer/changes"
	echo
	echo 'This can be caused by manual changes or due to a previous failed run.'
	echo 'Please investigate the situation, revert or commit the changes, and try again.'
	exit 1
fi >&2

printf 'commit transaction %s\n' "${transaction_name}" >>"${__messages_out:?}"

cat <<CODE
rollback() {
	uci changes \\
	| sed -e 's/\..*\$//' -e 's/^-//' \\
	| while read -r package
	  do
		  uci revert "\${package}"
	  done
}

uci batch <<'EOF' && uci commit || rollback
$(cat "${batchfile}")
EOF
CODE
