#!/bin/sh
# Copyright (C) 2015  Bogatov Dmitry <KAction@gnu.org>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -ue

hostname="$__object_id"
state="$(cat "$__object/parameter/state")"
marker="# __hosts/$hostname"

set -- "__hosts/$hostname" --file /etc/hosts --state "$state"

if [ "$state" = absent ] ; then
	__line "$@" --regex "$marker"
else
	ip="$(cat "$__object/parameter/ip")"
	__line "$@" --line "$ip $hostname $marker"
fi
