#!/bin/sh -e
#
# Copyright (C) 2015  Bogatov Dmitry <KAction@gnu.org>
# 2019 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#

set -e

hostname=$__object_id
state=$(cat "${__object}/parameter/state")
marker="# __hosts/${hostname}"

if test "${state}" != 'absent'
then
	ip=$(cat "${__object}/parameter/ip")
	if test -s "${__object}/parameter/alias"
	then
		aliases=$(while read -r a; do printf '\t%s' "$a"; done <"$__object/parameter/alias")
	fi

	set -- --line "$(printf '%s\t%s%s  %s' \
		"${ip}" "${hostname}" "${aliases}" "${marker}")"
else
	set -- --regex "$(echo "${marker}" | sed -e 's/\./\\./')$"
fi

__line "/etc/hosts:${hostname}" --file /etc/hosts --state "${state}" "$@"
