#!/bin/sh
#
# 2011 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Manage packages with yum (mostly Fedora)
#

if [ -f "$__object/parameter/name" ]; then
   name="$__object/parameter/name"
else
   name="$__object_id"
fi

state="$(cat "$__object/parameter/state")"

opts="-n -q"

not_installed="^no package provides"

case "$state" in
   installed)
      if grep -q "$not_installed" "$__object/explorer/pkg_version"; then
         echo zypper $opts install \"$name\"
      fi
   ;;
   removed)
      if ! grep -q "$not_installed" "$__object/explorer/pkg_version"; then
         echo zypper $opts remove \"$name\"
      fi
   ;;
   *)
      echo "Unknown state: $state" >&2
      exit 1
   ;;
esac
