#!/bin/sh

go_executable=$(cat "$__object/explorer/go-executable")
[ -z "$go_executable" ] && echo "__go_get: Cannot find go executable; make sure it is installed and in PATH" >&2 && exit 1

os=$(cat "$__global/explorer/os")
case $os in
	debian|devuan|ubuntu)
		__package build-essential
		;;
	*)
		echo "__go_get: Don't know how to install g++ on $os" >&2
		echo "__go_get: Send a pull request or contact <kamila@ksp.sk> to add support for $os." >&2
		exit 1
		;;
esac

__package git
