#!/bin/sh
#
# Copyright (C) 2011 Daniel Maher (phrawzty+cdist at gmail.com)
#
# This file is part of cdist (https://github.com/telmich/cdist/).
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

source="$(cat "$__object/parameter/source")"
destination="$(cat "$__object/parameter/destination")"

# The system binary is probably ok, but if not...
if [ -f "$__object/parameter/rsyncbin" ]; then
    rsyncbin="$(cat "$__object/parameter/rsyncbin")"
else
    rsyncbin=`which rsync`
fi

args='-a --stats'

# If the --delete argument should be passed to rsync.
if [ -f "$__object/parameter/delete" ]; then
    args="$args --delete"
fi

# Run rsync (locally).
echo "$rsyncbin $args $source root@$__target_host:$destination"
