#!/bin/sh -e
#
# 2018-2019 Thomas Eckert (tom at it-eckert.de)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.

state=$(cat "$__object/parameter/state")
servers=$(cat "$__object/parameter/servers")

os=$(cat "$__global/explorer/os")
case "$os" in
	debian|ubuntu)
		:
	;;
	*)
		echo "Your operating system ($os) is currently not supported by this type (${__type##*/})." >&2
		echo "Please contribute an implementation for it if you can." >&2
		exit 1
	;;
esac

__package xymon-client --state "$state"

if [ -f "$__object/parameter/msgcache" ]; then
	require="__package/xymon-client" __line /etc/xymon/clientlaunch.cfg \
		--regex DISABLED --state absent
fi

require="__package/xymon-client" __key_value CLIENTHOSTNAME \
	--file /etc/default/xymon-client \
	--value "'$__target_hostname'" \
	--delimiter '=' \
	--state "$state"
require="__package/xymon-client" __key_value XYMONSERVERS \
	--file /etc/default/xymon-client \
	--value "'$servers'" \
	--delimiter '=' \
	--state "$state"

## CLI-usage often requires a shell:
require="__package/xymon-client" __user xymon --shell "/bin/bash" --state "$state"
