#!/bin/sh -e
#
# 2014 Ricardo Catalinas Jiménez (jimenezrick at gmail.com)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#
# Update the package index with the appropriate package manager
#

type=$(cat "$__object/explorer/type")
currage="$(cat "$__object/explorer/currage")"
if [ -f "$__object/parameter/maxage" ]; then
    maxage="$(cat "$__object/parameter/maxage")"
fi

if [ -n "$maxage" ]; then
    if [ "$type" != "apt" ] && [ "$type" != "pacman" ]; then
        echo "ERROR: \"--maxage\" only supported for \"apt\" or \"pacman\" pkg-manager." >&2
        exit 1
    elif [ "$currage" -lt "$maxage" ]; then
        exit 0 # no need to update
    fi
fi


case "$type" in
    yum) ;;
    apt)
        echo "apt-get --quiet update"
        echo "apt-cache updated (age was: $currage)" >> "$__messages_out"
        ;;
    pacman)
        echo "pacman --noprogressbar --sync --refresh"
        echo "pacman package database synced (age was: $currage)" >> "$__messages_out"
        ;;
    *)
        echo "Don't know how to manage packages for type: $type" >&2
        exit 1
        ;;
esac
