#!/bin/sh
#
# 2013 Nico Schottelius (nico-cdist at schottelius.org)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#
#

directory="$__object_id"

if [ -f "$__object/parameter/shell" ]; then
   shell="--shell $(cat "$__object/parameter/shell")"
else
   shell=""
fi

username="$(cat "$__object/parameter/username")"

branch="$(cat "$__object/parameter/branch")"

source="$(cat "$__object/parameter/source")"

# Currently hardcoded - if anyone cares, make a parameter
# out of it
home=/home/$username

__user "$username" --home "$home" $shell

require="__user/$username" __directory "$home" \
    --owner "$username"

require="__user/$username __directory/$home" __git "$directory" \
    --source "$source" \
    --owner "$username" --branch "$branch"
